import {ImageResponse} from 'next/og';
export const runtime='edge';export const alt='Daily Yahrzeits — Diamant Solutions';export const size={width:1200,height:630};export const contentType='image/png';
const blue='#0868df',navy='#031442';
export default function Image(){return new ImageResponse(<div style={{width:'100%',height:'100%',display:'flex',flexDirection:'column',background:'white',fontFamily:'Arial',color:navy}}>
<div style={{height:480,display:'flex',position:'relative',overflow:'hidden'}}>
<div style={{width:'58%',display:'flex',flexDirection:'column',padding:'24px 34px',zIndex:2,background:'linear-gradient(105deg,#fff 0%,#fff 78%,#ffffffd8 91%,#ffffff00 100%)'}}>
<div style={{display:'flex',alignItems:'center',gap:13}}><div style={{width:72,height:72,border:'6px solid #0870e8',borderRadius:13,display:'flex',alignItems:'center',justifyContent:'center',fontSize:39,color:blue}}>◆</div><div style={{display:'flex',flexDirection:'column',fontWeight:900,lineHeight:.88}}><span style={{fontSize:41}}>DIAMANT</span><span style={{fontSize:32}}>SOLUTIONS</span></div></div>
<div style={{fontSize:12,fontWeight:800,marginTop:8,letterSpacing:.5}}>WEBSITES&nbsp;&nbsp; | &nbsp;&nbsp;BUSINESS MANAGEMENT SOFTWARE&nbsp;&nbsp; | &nbsp;&nbsp;BUSINESS ADVISORY</div>
<div style={{fontSize:77,fontWeight:900,lineHeight:.86,marginTop:30}}>DAILY</div><div style={{fontSize:74,fontWeight:900,lineHeight:.9,color:blue}}>YAHRZEITS</div>
<div style={{fontSize:27,fontWeight:700,lineHeight:1.12,marginTop:14}}>Remembering notable Jewish<br/>lives and their legacy.</div><div style={{width:55,height:4,background:blue,marginTop:12}}/></div>
<img src="https://funeral.com/cdn/shop/articles/yahrzeit-candle-guide-when-to-light-how-long-it-burns-and-what-to-do-for-yizkor-6240247.jpg?v=1769719869" width="600" height="480" style={{position:'absolute',right:0,top:0,width:600,height:480,objectFit:'cover'}}/>
<div style={{position:'absolute',right:0,top:0,width:410,height:98,background:blue,display:'flex',alignItems:'center',paddingLeft:54,color:'white',fontSize:20,lineHeight:1.15}}>BESPOKE SOLUTIONS<br/>FOR REAL BUSINESSES</div></div>
<div style={{height:150,display:'flex',alignItems:'center',justifyContent:'space-around',padding:'8px 28px',background:'#fff'}}>
{[['▣','ANY DATE','Browse previous, current\nor upcoming dates.'],['▤','HEBREW & ENGLISH','Clear Hebrew and\nEnglish details.'],['♙','NOTABLE LIVES','Rabbonim, authors,\nleaders and more.'],['⌕','EASY TO BROWSE','Quickly discover who is\nremembered today.']].map((x,i)=><div key={x[1]} style={{width:'24%',height:115,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',borderLeft:i?'1px solid #1680ee':'none',textAlign:'center'}}><div style={{fontSize:31,color:blue}}>{x[0]}</div><b style={{fontSize:16,marginTop:3}}>{x[1]}</b><span style={{whiteSpace:'pre-line',fontSize:13,lineHeight:1.12,marginTop:3}}>{x[2]}</span></div>)}</div></div>,size)}