"use client";
import {useEffect,useMemo,useState} from "react";
type Item={id?:string;name:string;category:string;unit:string;cost_net?:number|null;cost_vat_rate?:number;pricing_method?:string;markup_percent?:number|null;margin_percent?:number|null;fixed_sell_net?:number|null;active?:boolean};
const empty:Item={name:"",category:"Materials",unit:"each",cost_net:null,cost_vat_rate:20,pricing_method:"markup",markup_percent:30,active:true};
function sell(i:Item){const c=Number(i.cost_net||0);if(i.pricing_method==="fixed")return Number(i.fixed_sell_net||0);if(i.pricing_method==="margin"){const m=Number(i.margin_percent||0)/100;return m>=1?0:c/(1-m)}return c*(1+Number(i.markup_percent||0)/100)}
const gbp=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n||0);
export default function PriceBook(){const[data,setData]=useState<any>({items:[],labour:[]}),[edit,setEdit]=useState<Item|null>(null),[tab,setTab]=useState<"items"|"labour">("items"),[q,setQ]=useState(""),[msg,setMsg]=useState("");const load=()=>fetch("/api/admin/price-book",{cache:"no-store"}).then(async r=>{const b=await r.json();if(r.ok)setData(b);else setMsg(b.error||"Could not load Price Book")});useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>(data.items||[]).filter((x:Item)=>(x.name+" "+x.category).toLowerCase().includes(q.toLowerCase())),[data,q]);
 async function save(){if(!edit?.name.trim())return;const r=await fetch("/api/admin/price-book/item",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(edit)}),b=await r.json();if(!r.ok){setMsg(b.error||"Could not save");return}setEdit(null);setMsg("Saved");void load()}
 return <main className="mx-auto max-w-[1500px] px-4 py-6 lg:px-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Price Book</h1><p className="mt-1 text-sm text-black/55">Reusable materials, products and labour rates for fast, consistent estimating.</p></div><button onClick={()=>setEdit({...empty})} className="rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white">+ Add item</button></div>
 <div className="mt-5 flex gap-2"><button onClick={()=>setTab("items")} className={"rounded-xl px-4 py-2 text-sm font-black "+(tab==="items"?"bg-black text-white":"border bg-white")}>Items</button><button onClick={()=>setTab("labour")} className={"rounded-xl px-4 py-2 text-sm font-black "+(tab==="labour"?"bg-black text-white":"border bg-white")}>Labour</button></div>
 {msg&&<p className="mt-4 rounded-xl bg-white p-3 text-sm font-bold shadow-sm">{msg}</p>}
 {tab==="items"?<><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search steel, mesh, hinges, automation..." className="mt-5 w-full rounded-xl border border-black/15 bg-white px-4 py-3 outline-none"/>
 <div className="mt-4 overflow-hidden rounded-2xl border border-black/10 bg-white shadow-sm"><div className="hidden grid-cols-[1.6fr_1fr_.55fr_.7fr_.7fr_.65fr] gap-3 border-b bg-black/[.03] px-4 py-3 text-xs font-black uppercase tracking-wide text-black/45 md:grid"><span>Item</span><span>Category</span><span>Unit</span><span>Cost net</span><span>Default sell</span><span></span></div>{rows.map((i:Item)=><button key={i.id} onClick={()=>setEdit({...i})} className="grid w-full gap-1 border-b border-black/5 px-4 py-3 text-left hover:bg-black/[.02] md:grid-cols-[1.6fr_1fr_.55fr_.7fr_.7fr_.65fr] md:items-center md:gap-3"><b>{i.name}</b><span className="text-sm text-black/55">{i.category}</span><span className="text-sm">{i.unit}</span><span className="text-sm">{i.cost_net==null?"Not set":gbp(Number(i.cost_net))}</span><span className="text-sm font-bold">{i.cost_net==null&&i.pricing_method!=="fixed"?"—":gbp(sell(i))}</span><span className="text-xs font-black">Edit</span></button>)}</div></>:<div className="mt-5 grid gap-3">{(data.labour||[]).map((l:any)=><div key={l.id} className="rounded-2xl border border-black/10 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><b>{l.name}</b><p className="text-sm text-black/50">{l.person_name||"Standard rate"} · per {l.unit}</p></div><div className="text-right"><b>{Number(l.cost_rate)?gbp(Number(l.cost_rate)):"Cost not set"}</b><p className="text-xs text-black/45">50% default markup where configured</p></div></div></div>)}</div>}
 {edit&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-3 sm:items-center"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">{edit.id?"Edit item":"Add item"}</h2><button onClick={()=>setEdit(null)} className="font-black">Close</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["Name","name"],["Category","category"],["Unit (metre, each, panel, sheet...)","unit"],["Cost price net of VAT","cost_net"],["Cost VAT %","cost_vat_rate"]].map(([label,key])=><label key={key} className={key==="name"?"sm:col-span-2":""}><span className="text-xs font-black">{label}</span><input value={(edit as any)[key]??""} type={key.includes("cost")?"number":"text"} step="0.01" onChange={e=>setEdit({...edit,[key]:e.target.type==="number"?(e.target.value===""?null:Number(e.target.value)):e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label>)}<label><span className="text-xs font-black">Pricing method</span><select value={edit.pricing_method} onChange={e=>setEdit({...edit,pricing_method:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="markup">Markup on cost</option><option value="margin">Target gross margin</option><option value="fixed">Fixed selling price</option></select></label><label><span className="text-xs font-black">{edit.pricing_method==="fixed"?"Fixed sell net":edit.pricing_method==="margin"?"Gross margin %":"Markup %"}</span><input type="number" step="0.1" value={edit.pricing_method==="fixed"?edit.fixed_sell_net??"":edit.pricing_method==="margin"?edit.margin_percent??"":edit.markup_percent??""} onChange={e=>{const v=e.target.value===""?null:Number(e.target.value);setEdit({...edit,[edit.pricing_method==="fixed"?"fixed_sell_net":edit.pricing_method==="margin"?"margin_percent":"markup_percent"]:v})}} className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label></div><div className="mt-4 rounded-xl bg-black/[.04] p-3 text-sm"><b>Calculated default sell: {edit.cost_net==null&&edit.pricing_method!=="fixed"?"Set a cost first":gbp(sell(edit))}</b><p className="mt-1 text-black/50">Internal costs are stored net of VAT. VAT remains recorded separately.</p></div><button onClick={()=>void save()} className="mt-4 w-full rounded-xl bg-black px-4 py-3 font-black text-white">Save item</button></div></div>}</main>}