"use client";
import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
const cls="h-11 w-full rounded-xl border border-black/15 bg-white px-3 text-sm outline-none focus:border-[#e66a24]";
const fmt=(v?:string)=>v?new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"No date";
const local=(v?:string)=>{if(!v)return"";const d=new Date(v),p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
export default function TasksPanel({demo=false}:{demo?:boolean}){
 const searchParams=useSearchParams();
 const [data,setData]=useState<any>({tasks:[],users:[],jobs:[],preferences:{}}),[accent,setAccent]=useState("#e66a24"),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[editing,setEditing]=useState<any>(null),[detail,setDetail]=useState<any>(null),[updating,setUpdating]=useState<string>(""),[updatingAction,setUpdatingAction]=useState<string>(""),[filter,setFilter]=useState("mine"),[q,setQ]=useState(""),[err,setErr]=useState("");
 const api=demo?"/api/bms-demo/tasks":"/api/business-software/tasks";
 const load=async()=>{const r=await fetch(api,{cache:"no-store"});const b=await r.json();if(r.ok)setData({...b,tasks:Array.isArray(b?.tasks)?b.tasks:[],users:Array.isArray(b?.users)?b.users:[],jobs:Array.isArray(b?.jobs)?b.jobs:[]});else setErr(b.error||"Unable to load tasks");setLoading(false)};
 useEffect(()=>{try{const cfg=JSON.parse(sessionStorage.getItem("bms-tenant-config")||"{}");if(cfg?.accentColour)setAccent(String(cfg.accentColour));}catch{}void load()},[]);
 useEffect(()=>{const view=searchParams.get("view");if(view&&["attention","mine","business","waiting","upcoming","completed","all","overdue","today"].includes(view))setFilter(view);const task=searchParams.get("task");if(task&&data.tasks?.length){const found=data.tasks.find((t:any)=>String(t.id)===task);if(found)setDetail(found)}},[searchParams,data.tasks]);
 const tasks=useMemo(()=>(Array.isArray(data.tasks)?data.tasks:[]).filter((t:any)=>{const ids=(Array.isArray(t.assignee_user_ids)&&t.assignee_user_ids.length?t.assignee_user_ids:[t.assignee_user_id]).filter(Boolean),mine=ids.includes(data.currentUser?.id),active=["open","waiting"].includes(t.status),due=t.due_at?new Date(t.due_at).getTime():null,end=new Date();end.setHours(23,59,59,999);if(filter==="attention"&&(!active||!due||due>end.getTime()))return false;if(filter==="overdue"&&(!active||!due||due>=Date.now()))return false;if(filter==="today"&&(!active||!due||due<Date.now()||due>end.getTime()))return false;if(filter==="upcoming"&&(!active||!due||due<=end.getTime()))return false;if(filter==="mine"&&(!active||!mine))return false;if(filter==="business"&&(!active||t.task_source!=="business"))return false;if(filter==="waiting"&&t.status!=="waiting")return false;if(filter==="completed"&&t.status!=="completed")return false;if(filter==="all"&&false)return false;const s=(t.title+" "+(t.description||"")+" "+(t.waiting_on||"")).toLowerCase();return !q||s.includes(q.toLowerCase())}).sort((a:any,b:any)=>{const ad=a.due_at?new Date(a.due_at).getTime():9e15,bd=b.due_at?new Date(b.due_at).getTime():9e15;return ad-bd}),[data.tasks,data.currentUser,filter,q]);
 const save=async(e:any)=>{e.preventDefault();if(saving)return;setSaving(true);setErr("");try{const f=new FormData(e.currentTarget),obj:any=Object.fromEntries(f.entries());obj.assignee_user_ids=f.getAll("assignee_user_ids").map(String).filter(Boolean);obj.remind_in_app=true;obj.remind_email=f.get("remind_email")==="on";const iso=(v:any)=>{if(!v)return null;const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()};obj.due_at=iso(obj.due_at);obj.reminder_at=iso(obj.reminder_at);const method=editing?.id?"PATCH":"POST";if(editing?.id)obj.id=editing.id;if(demo){setOpen(false);setEditing(null);return}const r=await fetch(api,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(obj)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Unable to save task");setOpen(false);setEditing(null);await load()}catch(x:any){setErr(x?.message||"Unable to save task. Please try again.")}finally{setSaving(false)}};
 const patch=async(id:string,p:any)=>{if(demo)return;setErr("");const actedFromDetail=detail?.id===id;setUpdating(id);setUpdatingAction(p.snooze_days?`snooze-${p.snooze_days}`:p.status==="completed"?"complete":p.status==="archived"?"archive":p.status==="open"?"reopen":"update");const prevTasks=data.tasks,prevDetail=detail;let optimisticDue:string|null=null;if(p.snooze_days){const d=new Date();d.setDate(d.getDate()+Number(p.snooze_days));d.setHours(9,0,0,0);optimisticDue=d.toISOString()}else if(p.due_at)optimisticDue=p.due_at;if(optimisticDue){setData((x:any)=>({...x,tasks:x.tasks.map((t:any)=>t.id===id?{...t,due_at:optimisticDue,reminder_at:optimisticDue}:t)}));setDetail((x:any)=>x?.id===id?{...x,due_at:optimisticDue,reminder_at:optimisticDue}:x)}if(p.status==="completed"){setData((x:any)=>({...x,tasks:x.tasks.map((t:any)=>t.id===id?{...t,status:"completed"}:t)}));if(detail?.id===id)setDetail(null)}try{const r=await fetch(api,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...p})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Unable to update task");if(actedFromDetail&&(p.snooze_days||p.status==="completed"||p.status==="archived"))setDetail(null);await load()}catch(x:any){setData((x:any)=>({...x,tasks:prevTasks}));setDetail(prevDetail);setErr(x?.message||"Unable to update task. Please try again.")}finally{setUpdating("");setUpdatingAction("")}};
 const show=async(id:string)=>{setErr("");const localTask=(Array.isArray(data.tasks)?data.tasks:[]).find((x:any)=>x.id===id)||null;if(localTask)setDetail(localTask);if(demo||id.startsWith("job:"))return;try{const r=await fetch(api+"?id="+encodeURIComponent(id),{cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok||!b.task)throw new Error(b.error||"Unable to open task");setDetail((current:any)=>current?.id===id?{...current,...b.task}:current)}catch(x:any){if(!localTask)setDetail(null);setErr(x?.message||"Unable to load full task details. Please try again.")}};
 const attach=async(e:any)=>{e.preventDefault();if(!detail?.id)return;const fd=new FormData(e.currentTarget),r=await fetch("/api/business-software/tasks/attachments",{method:"POST",body:fd}),b=await r.json().catch(()=>({}));if(!r.ok){setErr(b.error||"Unable to upload attachment");return}e.currentTarget.reset();await show(detail.id)};
 const removeAttachment=async(id:string)=>{if(!detail?.id)return;const r=await fetch("/api/business-software/tasks/attachments?id="+encodeURIComponent(id),{method:"DELETE"});if(!r.ok){setErr("Unable to delete attachment");return}await show(detail.id)};
 const note=async(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget),body=String(f.get("body")||"");await fetch(api,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"note",task_id:detail.id,body})});e.currentTarget.reset();await show(detail.id)};
 const del=async(id:string)=>{if(!confirm("Delete this task permanently?"))return;await fetch("/api/business-software/tasks?id="+encodeURIComponent(id),{method:"DELETE"});setDetail(null);await load()};
 const user=(id:string)=>(Array.isArray(data.users)?data.users:[]).find((x:any)=>x.id===id)?.display_name||(Array.isArray(data.users)?data.users:[]).find((x:any)=>x.id===id)?.email||"Unassigned";
 const job=(id:string)=>(Array.isArray(data.jobs)?data.jobs:[]).find((x:any)=>x.id===id)?.reference;
 const dueClass=(t:any)=>{if(t.status==="completed")return "bg-green-100 text-green-800";if(!t.due_at)return "bg-slate-100 text-slate-600";const d=new Date(t.due_at),now=new Date(),end=new Date();end.setHours(23,59,59,999);if(d<now)return "bg-red-100 text-red-800";if(d<=end)return "bg-amber-100 text-amber-800";return "bg-blue-100 text-blue-800"};
 const priorityClass=(p:any)=>String(p)==="urgent"?"bg-red-100 text-red-800":String(p)==="high"?"bg-amber-100 text-amber-800":String(p)==="low"?"bg-slate-100 text-slate-600":"bg-blue-50 text-blue-700";
 const sourceClass=(t:any)=>t.task_source==="business"?"text-orange-800":"text-indigo-700";
 const cardClass=(t:any)=>t.task_source==="business"?"border-orange-200 bg-orange-50/55":String(t.priority)==="urgent"?"border-red-200 bg-red-50/60":"border-indigo-100 bg-indigo-50/35";
 if(loading)return <main className="mx-auto max-w-6xl p-4 md:p-8">Loading tasks…</main>;
 return <main className="mx-auto max-w-6xl p-3 pb-24 md:p-8">
  <div className="mb-5 flex items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Tasks</h1><p className="text-sm text-black/55">Job next actions and your own tasks, clearly organised.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="rounded-xl bg-[#e66a24] px-4 py-3 text-sm font-black text-white">+ Add task</button></div>
  {err&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{err}</div>}
  
  <div className="mb-4 grid gap-2 sm:grid-cols-[1fr_auto]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tasks" className={cls}/><div className="flex gap-1 overflow-x-auto">{[["attention","Needs Attention"],["mine","My Tasks"],["business","Job next actions"],["waiting","Waiting"],["upcoming","Upcoming"],["completed","Completed"],["all","All"]].map(([x,label])=><button key={x} onClick={()=>setFilter(x)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-black ${filter===x?"bg-black text-white":"bg-black/5"}`}>{label}</button>)}</div></div>
  <div className="mb-4 grid grid-cols-3 gap-2">{(()=>{const all=Array.isArray(data.tasks)?data.tasks:[],now=Date.now(),end=new Date();end.setHours(23,59,59,999);const active=all.filter((t:any)=>["open","waiting"].includes(t.status)),cards=[[active.filter((t:any)=>t.due_at&&new Date(t.due_at).getTime()<now).length,"Overdue","overdue","bg-red-50 border-red-200 text-red-800"],[active.filter((t:any)=>t.due_at&&new Date(t.due_at).getTime()>=now&&new Date(t.due_at).getTime()<=end.getTime()).length,"Due today","today","bg-amber-50 border-amber-200 text-amber-800"],[active.filter((t:any)=>t.due_at&&new Date(t.due_at).getTime()>end.getTime()).length,"Upcoming","upcoming","bg-blue-50 border-blue-200 text-blue-800"]];return cards.map(([n,l,v,colour]:any)=><button key={v} onClick={()=>setFilter(v)} className={`rounded-xl border p-3 text-left ${colour} ${filter===v?"ring-2 ring-black/20":""}`}><div className="text-xl font-black">{n}</div><div className="text-xs font-bold">{l}</div></button>)})()}</div><div className="grid gap-3">{tasks.map((t:any)=><article key={t.id} onClick={()=>show(t.id)} className={`cursor-pointer rounded-xl border p-4 shadow-sm transition hover:shadow-md ${cardClass(t)}`}>
   <button onClick={e=>{e.stopPropagation();show(t.id)}} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-base font-black leading-tight">{t.title}</div>{t.task_source==="business"?<><div className="mt-2 text-sm font-black text-black/80">{t.customer?.name||"Customer"}</div><div className="mt-0.5 text-sm text-black/60">{[t.job_reference||job(t.linked_job_id),t.job_type].filter(Boolean).join(" · ")}</div>{t.job_requirements&&<div className="mt-1 line-clamp-1 text-xs text-black/45">{t.job_requirements}</div>}</>:t.description&&<div className="mt-1 line-clamp-2 text-sm text-black/55">{t.description}</div>}</div><span className={`shrink-0 rounded-md px-2 py-1 text-[11px] font-black ${dueClass(t)}`}>{t.status==="waiting"?"Waiting":fmt(t.due_at)}</span></div>
   <div className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-1 border-t border-black/[.07] pt-2.5 text-xs"><span className={`font-black ${sourceClass(t)}`}>{t.task_source==="business"?"Job next action":t.recurrence!=="none"?"Recurring task":"Task"}</span><span className="text-black/25">•</span><span className={`font-black capitalize ${String(t.priority)==="urgent"?"text-red-700":String(t.priority)==="high"?"text-amber-700":"text-black/50"}`}>{t.priority||"normal"}</span><span className="text-black/25">•</span><span className="text-black/50">{(Array.isArray(t.assignee_user_ids)&&t.assignee_user_ids.length?t.assignee_user_ids:[t.assignee_user_id]).filter(Boolean).map((id:string)=>user(id)).join(", ")||"Unassigned"}</span>{t.recurrence!=="none"&&<span className="capitalize text-black/50">· {t.recurrence}</span>}{t.waiting_on&&<span className="text-black/50">· Waiting on {t.waiting_on}</span>}</div></button>
   <div className="mt-3 flex flex-wrap items-center gap-2">{!["completed","archived"].includes(t.status)&&<><button disabled={updating===t.id} onClick={e=>{e.stopPropagation();void patch(t.id,{status:"completed"})}} className="h-9 rounded-lg bg-[#183f2b] px-4 text-xs font-black text-white disabled:opacity-60">{updating===t.id&&updatingAction==="complete"?"Saving…":"Complete"}</button><span className="ml-1 text-xs font-black text-black/45">Snooze</span>{[1,3,7].map(days=><button disabled={updating===t.id} key={days} onClick={e=>{e.stopPropagation();if(t.task_source==="business")void patch(t.id,{snooze_days:days});else {const d=new Date();d.setDate(d.getDate()+days);d.setHours(9,0,0,0);void patch(t.id,{snoozed_until:d.toISOString(),due_at:d.toISOString(),reminder_at:d.toISOString()})}}} className="h-9 rounded-lg border border-black/10 bg-white px-3 text-xs font-black disabled:opacity-60">{updating===t.id&&updatingAction===`snooze-${days}`?"Saving…":`${days} day${days===1?"":"s"}`}</button>)}</>}{t.task_source!=="business"&&<button onClick={e=>{e.stopPropagation();setEditing(t);setOpen(true)}} className="h-9 rounded-lg border border-black/15 bg-white px-4 text-xs font-black text-black/70">Edit</button>}{t.status==="completed"&&<button onClick={e=>{e.stopPropagation();void patch(t.id,{status:"open"})}} className="rounded-lg bg-black/5 px-3 py-2 text-xs font-black">Reopen</button>}</div>
  </article>)}</div>
  {!tasks.length&&<div className="rounded-2xl border border-dashed border-black/20 p-10 text-center text-sm text-black/50">No tasks in this view.</div>}
  {open&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-4"><form onSubmit={save} className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl">
   <div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">{editing?"Edit task":"New task"}</h2><button type="button" onClick={()=>setOpen(false)} className="text-2xl">×</button></div>
   {err&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{err}</div>}<div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><b className="mb-1 block text-xs">Task</b><input name="title" required defaultValue={editing?.title||""} className={cls}/></label><label className="sm:col-span-2"><b className="mb-1 block text-xs">Notes / description</b><textarea name="description" defaultValue={editing?.description||""} className={cls+" min-h-24 py-3"}/></label>
   <fieldset><b className="mb-2 block text-xs">Assigned to</b><div className="space-y-2 rounded-xl border border-black/15 p-3">{(Array.isArray(data.users)?data.users:[]).map((u:any)=>{const ids=Array.isArray(editing?.assignee_user_ids)&&editing.assignee_user_ids.length?editing.assignee_user_ids:[editing?.assignee_user_id||data.currentUser?.id];return <label key={u.id} className="flex items-center gap-2 text-sm"><input type="checkbox" name="assignee_user_ids" value={u.id} defaultChecked={ids.includes(u.id)}/><span>{u.display_name||u.email}</span></label>})}</div></fieldset>
   <label><b className="mb-1 block text-xs">Priority</b><select name="priority" defaultValue={editing?.priority||"normal"} className={cls}>{["low","normal","high","urgent"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><b className="mb-1 block text-xs">Due</b><input type="datetime-local" name="due_at" defaultValue={local(editing?.due_at)} className={cls}/></label><label><b className="mb-1 block text-xs">Reminder</b><input type="datetime-local" name="reminder_at" defaultValue={local(editing?.reminder_at)} className={cls}/></label>
   <label><b className="mb-1 block text-xs">Linked job</b><select name="linked_job_id" defaultValue={editing?.linked_job_id||""} className={cls}><option value="">None</option>{(Array.isArray(data.jobs)?data.jobs:[]).map((j:any)=><option value={j.id} key={j.id}>{j.reference}</option>)}</select></label>
   <label><b className="mb-1 block text-xs">Repeat</b><select name="recurrence" defaultValue={editing?.recurrence||"none"} className={cls}>{["none","daily","weekly","monthly"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><b className="mb-1 block text-xs">Status</b><select name="status" defaultValue={editing?.status||"open"} className={cls}>{["open","waiting","completed","archived"].map(x=><option key={x}>{x}</option>)}</select></label><label><b className="mb-1 block text-xs">Waiting on</b><input name="waiting_on" defaultValue={editing?.waiting_on||""} placeholder="Customer, supplier…" className={cls}/></label>
   <label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="remind_email" defaultChecked={editing?!!editing.remind_email:true}/> Email reminder</label></div>
   <button type="submit" disabled={saving} className="mt-5 w-full rounded-xl bg-[#e66a24] py-3 font-black text-white disabled:opacity-60">{saving?"Saving…":"Save task"}</button></form></div>}
  {detail&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/60 p-3 md:p-6" onClick={()=>setDetail(null)}><section onClick={e=>e.stopPropagation()} className="max-h-[90dvh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl md:p-6">
   <div className="flex justify-between gap-3"><div className="min-w-0"><div className="text-[11px] font-black uppercase tracking-wide text-orange-700">{detail.task_source==="business"?"Job next action":detail.recurrence!=="none"?"Recurring task":"Task"}</div><h2 className="mt-1 text-2xl font-black leading-tight">{detail.title}</h2>{detail.task_source==="business"&&<><div className="mt-3 text-base font-black">{detail.customer?.name||"Customer"}</div><div className="mt-0.5 text-sm text-black/60">{[detail.job_reference||job(detail.linked_job_id),detail.job_type].filter(Boolean).join(" · ")}</div></>}<div className="mt-2 text-xs text-black/50">{(Array.isArray(detail.assignee_user_ids)&&detail.assignee_user_ids.length?detail.assignee_user_ids:[detail.assignee_user_id]).filter(Boolean).map((id:string)=>user(id)).join(", ")||"Unassigned"} · {fmt(detail.due_at)}</div></div><button onClick={()=>setDetail(null)} className="text-2xl">×</button></div>
   {detail.task_source==="business"?<div className="mt-5 rounded-xl border border-orange-100 bg-orange-50/60 p-4 text-sm"><div className="text-xs font-black uppercase tracking-wide text-black/45">Job details</div><div className="mt-2 text-black/60">Stage: <b className="font-bold text-black/75">{String(detail.job_status||"").replaceAll("_"," ")}</b></div>{detail.job_requirements&&<div className="mt-2 text-black/75">{detail.job_requirements}</div>}{detail.job_address&&<div className="mt-2 text-xs text-black/50">{detail.job_address}</div>}{detail.customer?.phone&&<div className="mt-2 text-xs font-bold">{detail.customer.phone}</div>}</div>:detail.description&&<p className="mt-5 whitespace-pre-wrap text-sm">{detail.description}</p>}
   <div className="mt-5 flex flex-wrap items-center gap-2">{!["completed","archived"].includes(detail.status)&&<><button disabled={updating===detail.id} onClick={()=>patch(detail.id,{status:"completed"})} className="rounded-lg bg-[#183f2b] px-4 py-2 text-xs font-black text-white disabled:opacity-60">{updating===detail.id&&updatingAction==="complete"?"Saving…":"Complete"}</button><div className="flex items-center gap-1"><span className="mr-1 text-xs font-black text-black/55">Snooze</span>{[1,3,7].map(days=><button disabled={updating===detail.id} key={days} onClick={()=>{if(detail.task_source==="business")void patch(detail.id,{snooze_days:days});else {const d=new Date();d.setDate(d.getDate()+days);d.setHours(9,0,0,0);void patch(detail.id,{snoozed_until:d.toISOString(),due_at:d.toISOString(),reminder_at:d.toISOString()})}}} className="rounded-lg border border-black/10 bg-white px-3 py-2 text-xs font-black disabled:opacity-60">{updating===detail.id&&updatingAction===`snooze-${days}`?"Saving…":`${days} day${days===1?"":"s"}`}</button>)}</div></>}{detail.task_source!=="business"&&<><button onClick={()=>{setEditing(detail);setOpen(true);setDetail(null)}} className="rounded-lg border border-black/10 bg-white px-3 py-2 text-xs font-black">Edit</button><button disabled={updating===detail.id} onClick={()=>patch(detail.id,{status:"archived"})} className="rounded-lg border border-black/10 bg-white px-3 py-2 text-xs font-black disabled:opacity-60">{updating===detail.id&&updatingAction==="archive"?"Saving…":"Archive"}</button><button onClick={()=>del(detail.id)} className="rounded-lg border border-black/10 bg-white px-3 py-2 text-xs font-black text-red-700">Delete</button></>}</div>
   <h3 className="mt-7 font-black">Attachments</h3><form onSubmit={attach} className="mt-2 flex items-center gap-2"><input type="hidden" name="task_id" value={detail.id}/><input type="file" name="file" required className="min-w-0 flex-1 text-sm"/><button className="rounded-xl px-4 py-2 text-sm font-black text-white" style={{backgroundColor:accent}}>Upload</button></form><div className="mt-3 space-y-2">{(detail.attachments||[]).map((a:any)=><div key={a.id} className="flex items-center justify-between gap-3 rounded-xl bg-black/[.04] p-3 text-sm"><a className="min-w-0 truncate font-bold underline" href={"/api/business-software/tasks/attachments?id="+encodeURIComponent(a.id)} target="_blank" rel="noreferrer">{a.file_name}</a><button onClick={()=>removeAttachment(a.id)} className="shrink-0 text-xs font-black text-red-700">Delete</button></div>)}</div>
   <h3 className="mt-7 font-black">Notes</h3><form onSubmit={note} className="mt-2 flex gap-2"><input name="body" required placeholder="Add a note…" className={cls}/><button className="rounded-xl px-4 text-sm font-black text-white" style={{backgroundColor:accent}}>Add</button></form>
   <div className="mt-3 space-y-2">{(detail.notes||[]).map((n:any)=><div key={n.id} className="rounded-xl bg-black/[.04] p-3 text-sm"><div>{n.body}</div><div className="mt-1 text-[11px] text-black/40">{fmt(n.created_at)}</div></div>)}</div>
   {(detail.events||[]).length?<><h3 className="mt-7 font-black">Activity</h3><div className="mt-2 space-y-2">{(detail.events||[]).map((e:any)=><div key={e.id} className="border-l-2 pl-3 text-xs" style={{borderColor:accent}}><b className="capitalize">{String(e.event_type).replaceAll("_"," ")}</b><div className="text-black/40">{fmt(e.created_at)}</div></div>)}</div></>:null}
   <div className="mt-7 border-t border-black/10 pt-4"><button onClick={()=>setDetail(null)} className="w-full rounded-xl py-3 text-sm font-black text-white" style={{backgroundColor:accent}}>Close</button></div>
  </section></div>}
 </main>
}