"use client";
import {useEffect,useMemo,useState} from "react";
const cls="h-11 w-full rounded-xl border border-black/15 bg-white px-3 text-sm outline-none focus:border-[#e66a24]";
const fmt=(v?:string)=>v?new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"No date";
const local=(v?:string)=>{if(!v)return"";const d=new Date(v),p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
export default function TasksPanel(){
 const [data,setData]=useState<any>({tasks:[],users:[],jobs:[],preferences:{}}),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[editing,setEditing]=useState<any>(null),[detail,setDetail]=useState<any>(null),[filter,setFilter]=useState("active"),[q,setQ]=useState(""),[err,setErr]=useState("");
 const load=async()=>{const r=await fetch("/api/business-software/tasks",{cache:"no-store"});const b=await r.json();if(r.ok)setData({...b,tasks:Array.isArray(b?.tasks)?b.tasks:[],users:Array.isArray(b?.users)?b.users:[],jobs:Array.isArray(b?.jobs)?b.jobs:[]});else setErr(b.error||"Unable to load tasks");setLoading(false)};
 useEffect(()=>{void load()},[]);
 const tasks=useMemo(()=>(Array.isArray(data.tasks)?data.tasks:[]).filter((t:any)=>{if(filter==="active"&&!["open","waiting"].includes(t.status))return false;if(filter!=="active"&&filter!=="all"&&t.status!==filter)return false;const s=(t.title+" "+(t.description||"")+" "+(t.waiting_on||"")).toLowerCase();return !q||s.includes(q.toLowerCase())}).sort((a:any,b:any)=>{const ad=a.due_at?new Date(a.due_at).getTime():9e15,bd=b.due_at?new Date(b.due_at).getTime():9e15;return ad-bd}),[data.tasks,filter,q]);
 const save=async(e:any)=>{e.preventDefault();if(saving)return;setSaving(true);setErr("");try{const f=new FormData(e.currentTarget),obj:any=Object.fromEntries(f.entries());obj.remind_in_app=f.get("remind_in_app")==="on";obj.remind_email=f.get("remind_email")==="on";const iso=(v:any)=>{if(!v)return null;const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()};obj.due_at=iso(obj.due_at);obj.reminder_at=iso(obj.reminder_at);const method=editing?.id?"PATCH":"POST";if(editing?.id)obj.id=editing.id;const r=await fetch("/api/business-software/tasks",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(obj)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Unable to save task");setOpen(false);setEditing(null);await load()}catch(x:any){setErr(x?.message||"Unable to save task. Please try again.")}finally{setSaving(false)}};
 const patch=async(id:string,p:any)=>{await fetch("/api/business-software/tasks",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...p})});await load();if(detail?.id===id)await show(id)};
 const show=async(id:string)=>{const r=await fetch("/api/business-software/tasks?id="+encodeURIComponent(id),{cache:"no-store"});const b=await r.json();setDetail(b.task)};
 const note=async(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget),body=String(f.get("body")||"");await fetch("/api/business-software/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"note",task_id:detail.id,body})});e.currentTarget.reset();await show(detail.id)};
 const del=async(id:string)=>{if(!confirm("Delete this task permanently?"))return;await fetch("/api/business-software/tasks?id="+encodeURIComponent(id),{method:"DELETE"});setDetail(null);await load()};
 const user=(id:string)=>(Array.isArray(data.users)?data.users:[]).find((x:any)=>x.id===id)?.display_name||(Array.isArray(data.users)?data.users:[]).find((x:any)=>x.id===id)?.email||"Unassigned";
 const job=(id:string)=>(Array.isArray(data.jobs)?data.jobs:[]).find((x:any)=>x.id===id)?.reference;
 const dueClass=(t:any)=>t.status==="completed"?"bg-green-100 text-green-800":t.due_at&&new Date(t.due_at)<new Date()?"bg-red-100 text-red-800":"bg-black/5 text-black/60";
 if(loading)return <main className="mx-auto max-w-6xl p-4 md:p-8">Loading tasks…</main>;
 return <main className="mx-auto max-w-6xl p-3 pb-24 md:p-8">
  <div className="mb-5 flex items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Tasks & Notes</h1><p className="text-sm text-black/55">Follow-ups, reminders and internal work in one place.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="rounded-xl bg-[#e66a24] px-4 py-3 text-sm font-black text-white">+ Add task</button></div>
  {err&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{err}</div>}
  <div className="mb-4 grid gap-2 sm:grid-cols-[1fr_auto]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tasks and notes" className={cls}/><div className="flex gap-1 overflow-x-auto">{["active","waiting","completed","archived","all"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-black capitalize ${filter===x?"bg-black text-white":"bg-black/5"}`}>{x}</button>)}</div></div>
  <div className="grid gap-3">{tasks.map((t:any)=><article key={t.id} className="rounded-2xl border border-black/10 bg-white p-4 shadow-sm">
   <button onClick={()=>show(t.id)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-black">{t.title}</div>{t.description&&<div className="mt-1 line-clamp-2 text-sm text-black/55">{t.description}</div>}</div><span className={`shrink-0 rounded-full px-2 py-1 text-[11px] font-black ${dueClass(t)}`}>{t.status==="waiting"?"Waiting":fmt(t.due_at)}</span></div>
   <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-black/50"><span>{user(t.assignee_user_id)}</span><span className="capitalize">{t.priority}</span>{t.linked_job_id&&<span>Job {job(t.linked_job_id)}</span>}{t.recurrence!=="none"&&<span className="capitalize">{t.recurrence}</span>}{t.waiting_on&&<span>Waiting on: {t.waiting_on}</span>}</div></button>
   <div className="mt-3 flex gap-2">{!["completed","archived"].includes(t.status)&&<button onClick={()=>patch(t.id,{status:"completed"})} className="rounded-lg bg-green-100 px-3 py-2 text-xs font-black text-green-800">Complete</button>}<button onClick={()=>{setEditing(t);setOpen(true)}} className="rounded-lg bg-black/5 px-3 py-2 text-xs font-black">Edit</button>{t.status==="completed"&&<button onClick={()=>patch(t.id,{status:"open"})} className="rounded-lg bg-black/5 px-3 py-2 text-xs font-black">Reopen</button>}</div>
  </article>)}</div>
  {!tasks.length&&<div className="rounded-2xl border border-dashed border-black/20 p-10 text-center text-sm text-black/50">No tasks in this view.</div>}
  {open&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-4"><form onSubmit={save} className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl">
   <div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">{editing?"Edit task":"New task"}</h2><button type="button" onClick={()=>setOpen(false)} className="text-2xl">×</button></div>
   {err&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{err}</div>}<div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><b className="mb-1 block text-xs">Task</b><input name="title" required defaultValue={editing?.title||""} className={cls}/></label><label className="sm:col-span-2"><b className="mb-1 block text-xs">Notes / description</b><textarea name="description" defaultValue={editing?.description||""} className={cls+" min-h-24 py-3"}/></label>
   <label><b className="mb-1 block text-xs">Assigned to</b><select name="assignee_user_id" defaultValue={editing?.assignee_user_id||data.currentUser?.id} className={cls}>{(Array.isArray(data.users)?data.users:[]).map((u:any)=><option value={u.id} key={u.id}>{u.display_name||u.email}</option>)}</select></label>
   <label><b className="mb-1 block text-xs">Priority</b><select name="priority" defaultValue={editing?.priority||"normal"} className={cls}>{["low","normal","high","urgent"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><b className="mb-1 block text-xs">Due</b><input type="datetime-local" name="due_at" defaultValue={local(editing?.due_at)} className={cls}/></label><label><b className="mb-1 block text-xs">Reminder</b><input type="datetime-local" name="reminder_at" defaultValue={local(editing?.reminder_at)} className={cls}/></label>
   <label><b className="mb-1 block text-xs">Linked job</b><select name="linked_job_id" defaultValue={editing?.linked_job_id||""} className={cls}><option value="">None</option>{(Array.isArray(data.jobs)?data.jobs:[]).map((j:any)=><option value={j.id} key={j.id}>{j.reference}</option>)}</select></label>
   <label><b className="mb-1 block text-xs">Repeat</b><select name="recurrence" defaultValue={editing?.recurrence||"none"} className={cls}>{["none","daily","weekly","monthly"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><b className="mb-1 block text-xs">Status</b><select name="status" defaultValue={editing?.status||"open"} className={cls}>{["open","waiting","completed","archived"].map(x=><option key={x}>{x}</option>)}</select></label><label><b className="mb-1 block text-xs">Waiting on</b><input name="waiting_on" defaultValue={editing?.waiting_on||""} placeholder="Customer, supplier…" className={cls}/></label>
   <label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="remind_in_app" defaultChecked={editing?.remind_in_app!==false}/> In-app reminder</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="remind_email" defaultChecked={!!editing?.remind_email}/> Email reminder</label></div>
   <button type="submit" disabled={saving} className="mt-5 w-full rounded-xl bg-[#e66a24] py-3 font-black text-white disabled:opacity-60">{saving?"Saving…":"Save task"}</button></form></div>}
  {detail&&<div className="fixed inset-0 z-[110] flex justify-end bg-black/60"><section className="h-full w-full max-w-xl overflow-y-auto bg-white p-5">
   <div className="flex justify-between gap-3"><div><h2 className="text-xl font-black">{detail.title}</h2><div className="mt-1 text-xs text-black/50">{user(detail.assignee_user_id)} · {fmt(detail.due_at)}</div></div><button onClick={()=>setDetail(null)} className="text-2xl">×</button></div>
   {detail.description&&<p className="mt-5 whitespace-pre-wrap text-sm">{detail.description}</p>}
   <div className="mt-5 flex flex-wrap gap-2">{!["completed","archived"].includes(detail.status)&&<><button onClick={()=>patch(detail.id,{status:"completed"})} className="rounded-lg bg-green-100 px-3 py-2 text-xs font-black">Complete</button><button onClick={()=>patch(detail.id,{snoozed_until:new Date(Date.now()+86400000).toISOString(),reminder_at:new Date(Date.now()+86400000).toISOString()})} className="rounded-lg bg-black/5 px-3 py-2 text-xs font-black">Snooze 1 day</button></>}<button onClick={()=>{setEditing(detail);setOpen(true);setDetail(null)}} className="rounded-lg bg-black/5 px-3 py-2 text-xs font-black">Edit</button><button onClick={()=>patch(detail.id,{status:"archived"})} className="rounded-lg bg-black/5 px-3 py-2 text-xs font-black">Archive</button><button onClick={()=>del(detail.id)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-black text-red-700">Delete</button></div>
   <h3 className="mt-7 font-black">Notes</h3><form onSubmit={note} className="mt-2 flex gap-2"><input name="body" required placeholder="Add a note…" className={cls}/><button className="rounded-xl bg-black px-4 text-sm font-black text-white">Add</button></form>
   <div className="mt-3 space-y-2">{(detail.notes||[]).map((n:any)=><div key={n.id} className="rounded-xl bg-black/[.04] p-3 text-sm"><div>{n.body}</div><div className="mt-1 text-[11px] text-black/40">{fmt(n.created_at)}</div></div>)}</div>
   <h3 className="mt-7 font-black">Activity</h3><div className="mt-2 space-y-2">{(detail.events||[]).map((e:any)=><div key={e.id} className="border-l-2 border-[#e66a24]/30 pl-3 text-xs"><b className="capitalize">{String(e.event_type).replaceAll("_"," ")}</b><div className="text-black/40">{fmt(e.created_at)}</div></div>)}</div>
  </section></div>}
 </main>
}