'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
import './setup.css';

const steps=[
 {title:'Your business',fields:[['businessName','Business name'],['contactName','Your name'],['email','Email address'],['phone','Phone number'],['website','Website (if you have one)']]},
 {title:'What you do',fields:[['businessType','What does your business do?'],['workName','What do you call your work? (Jobs, Projects, Cases, Orders...)'],['workflow','Briefly describe what normally happens from a new enquiry through to completion.']]},
 {title:'What you need',fields:[['features','What would you like to manage in the system?'],['statuses','What stages or statuses do you currently use?'],['users','How many people will use the system?'],['roles','Do different staff need different access?']]},
 {title:'Documents & money',fields:[['quotes','How do you currently handle quotes?'],['invoices','How do you currently handle invoices and payments?'],['files','What files, photos or documents do you need to keep?'],['integrations','Any software you would like connected?']]},
 {title:'Branding & extras',fields:[['logo','Your logo'],['colours','Brand colours (if known)'],['dashboard','What would you most like to see on your dashboard?'],['anythingElse','Anything else we should know?']]}
];
const longKeys=['workflow','features','statuses','roles','quotes','invoices','files','integrations','dashboard','anythingElse','businessType'];
const plan=s=>s?{users:Math.max(2,Number(s.users)||2),ai:!!s.ai,interval:s.interval==='annual'?'annual':'monthly'}:{};

export default function SetupPage(){
 const [data,setData]=useState({}); const [step,setStep]=useState(0); const [saved,setSaved]=useState(false); const [selection,setSelection]=useState(null); const [session,setSession]=useState(null); const [tenantId,setTenantId]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [logoPath,setLogoPath]=useState('');
 const pct=useMemo(()=>Math.round(((step+1)/steps.length)*100),[step]);
 const update=(k,v)=>setData(x=>({...x,[k]:v}));
 useEffect(()=>{try{const raw=localStorage.getItem('ds-bms-onboarding');if(raw){const v=JSON.parse(raw);setData(v.data||{});setStep(Math.min(v.step||0,steps.length-1));}const rawPlan=localStorage.getItem('ds-bms-selection');if(rawPlan){const s=JSON.parse(rawPlan);setSelection(s);setData(x=>({...x,users:x.users||String(s.users||2)}));}}catch{}supabase.auth.getSession().then(({data:{session:s}})=>setSession(s));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{if(!session?.user)return;setBusy(true);supabase.from('tenant_members').select('tenant_id').eq('user_id',session.user.id).limit(1).single().then(async({data:m,error})=>{if(error){setMessage('We could not load your business account. Please refresh and try again.');setBusy(false);return;}setTenantId(m.tenant_id);const {data:o}=await supabase.from('onboarding').select('*').eq('tenant_id',m.tenant_id).single();if(o){setData(x=>({...x,...(o.answers||{})}));setStep(Math.min(o.current_step||0,steps.length-1));if(Object.keys(o.plan_selection||{}).length)setSelection(o.plan_selection);setLogoPath(o.logo_path||'');}setBusy(false);});},[session?.user?.id]);
 useEffect(()=>{if(!Object.keys(data).length)return;const t=setTimeout(async()=>{try{localStorage.setItem('ds-bms-onboarding',JSON.stringify({data,step,updatedAt:new Date().toISOString()}));}catch{}if(session&&tenantId){const {error}=await supabase.from('onboarding').update({answers:data,current_step:step,progress:pct,plan_selection:plan(selection),status:'in_progress'}).eq('tenant_id',tenantId);if(error){setMessage('Your latest change is saved on this device, but could not be saved online.');return;}}setSaved(true);setTimeout(()=>setSaved(false),1200);},450);return()=>clearTimeout(t);},[data,step,session,tenantId,pct,selection]);
 async function emailLink(e){e.preventDefault();if(!data.email)return;setBusy(true);const {error}=await supabase.auth.signInWithOtp({email:data.email,options:{emailRedirectTo:window.location.origin+'/setup',shouldCreateUser:true,data:{business_name:data.businessName||'My business',onboarding_answers:data,plan_selection:plan(selection)}}});setMessage(error?error.message:'Check your email for your secure sign-in link. It will bring you back here.');setBusy(false);}
 async function upload(file){if(!file||!tenantId)return;setBusy(true);const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=tenantId+'/logo-'+Date.now()+'.'+ext;const {error}=await supabase.storage.from('onboarding-assets').upload(path,file);if(error)setMessage(error.message);else{await supabase.from('onboarding').update({logo_path:path}).eq('tenant_id',tenantId);setLogoPath(path);setMessage('Logo uploaded securely.');}setBusy(false);}
 async function submit(){if(!session){setMessage('Use your secure email link first so we can attach this setup to your account.');return;}setBusy(true);const {error}=await supabase.from('onboarding').update({answers:data,current_step:4,progress:100,plan_selection:plan(selection),logo_path:logoPath||null,status:'submitted',submitted_at:new Date().toISOString()}).eq('tenant_id',tenantId);setMessage(error?'We could not submit your setup. Please try again.':'Submitted. We have everything you provided and can now prepare your Business Management Software.');setBusy(false);}
 return <main className="setupPage"><header className="setupHeader"><Link href="/"><img src="/DS Logo latest tagline.png" alt="Diamant Solutions"/></Link><span>{saved?'Saved':session?'Securely saved online':'Progress saves on this device'}</span></header><section className="setupWrap"><div className="setupIntro"><p>BUSINESS SOFTWARE SETUP</p><h1>Let’s set up your business.</h1><span>{session?'Your answers are securely saved to your business account.':'Answer what you can now. Use your secure email link to continue on any device.'}</span>{selection&&<div className="selectionSummary"><b>Your selection</b><span>{selection.users} users · {selection.ai?'AI Assistant included · ':''}{selection.interval==='annual'?'Annual billing':'Monthly billing'}</span></div>}</div>{!session&&<form className="secureAccount" onSubmit={emailLink}><div><b>Save and continue securely</b><span>We’ll email you a secure sign-in link. No password needed.</span></div><input type="email" value={data.email||''} onChange={e=>update('email',e.target.value)} placeholder="Email address" required/><button disabled={busy}>{busy?'Sending...':'Email my secure link'}</button></form>}{message&&<div className="setupMessage">{message}</div>}<div className="progress"><div><b>Step {step+1} of {steps.length}</b><span>{pct}% complete</span></div><i><em style={{width:pct+'%'}}/></i></div><div className="setupCard"><small>{steps[step].title.toUpperCase()}</small><h2>{steps[step].title}</h2>{steps[step].fields.map(([key,label])=><label key={key}><b>{label}</b>{key==='logo'?(session?<div className="logoUpload"><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>upload(e.target.files?.[0])}/>{logoPath&&<span>Uploaded ✓</span>}</div>:<div className="uploadNote">Use your secure email link above before uploading your logo.</div>):longKeys.includes(key)?<textarea value={data[key]||''} onChange={e=>update(key,e.target.value)} placeholder="Type your answer here..."/>:<input value={data[key]||''} onChange={e=>update(key,e.target.value)} placeholder="Type here..."/>}</label>)}<div className="setupActions">{step>0?<button className="secondary" onClick={()=>setStep(x=>x-1)}>Back</button>:<Link className="secondary" href="/">Back to website</Link>}<span>{session?'Saved securely as you go.':'Saved on this device as you go.'}</span>{step<4?<button onClick={()=>setStep(x=>x+1)}>Save & continue</button>:<button disabled={busy} onClick={submit}>{busy?'Saving...':'Submit my setup'}</button>}</div></div><p className="setupHelp">{session?'You can return later from another device using the same email address.':'You can keep filling this in now, then use the secure link before submitting.'}</p></section></main>;
}
