import {NextResponse} from 'next/server';
import crypto from 'crypto';
const SUPABASE_URL=process.env.DS_SUPABASE_URL||'https://iepqggrfenfqrqyzqyed.supabase.co';
const SERVICE_KEY=process.env.DS_SUPABASE_SERVICE_ROLE_KEY;
const WEBHOOK_SECRET=process.env.STRIPE_WEBHOOK_SECRET;
function verify(raw,header){if(!WEBHOOK_SECRET||!header)return false;const parts=Object.fromEntries(header.split(',').map(x=>x.split('=')));const t=parts.t,v1=header.split(',').find(x=>x.startsWith('v1='))?.slice(3);if(!t||!v1||Math.abs(Date.now()/1000-Number(t))>300)return false;const expected=crypto.createHmac('sha256',WEBHOOK_SECRET).update(t+'.'+raw).digest('hex');try{return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(v1))}catch{return false}}
async function upsertSession(s){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error('Supabase server configuration missing');const m=s.metadata||{},service=m.service_type==='website'?'website':'business_software',plan=m.plan_key||(service==='website'?'monthly':'business_software'),paid=s.payment_status==='paid'||(s.mode==='subscription'&&s.status==='complete'&&s.payment_status==='no_payment_required');const row={service_type:service,plan_key:plan,users:service==='business_software'?Math.max(2,Number(m.users)||2):null,ai_included:m.ai_included==='true',billing_interval:m.billing_interval||null,stripe_checkout_session_id:s.id,stripe_customer_id:typeof s.customer==='string'?s.customer:null,stripe_subscription_id:typeof s.subscription==='string'?s.subscription:null,customer_email:s.customer_details?.email||s.customer_email||null,payment_status:paid?'paid':'pending',paid_at:paid?new Date().toISOString():null,provisioning_status:service==='business_software'&&paid?'ready_for_setup':'not_started'};const r=await fetch(SUPABASE_URL+'/rest/v1/checkout_orders?on_conflict=stripe_checkout_session_id',{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error('Supabase fulfilment failed: '+await r.text())}
function stripeStatus(s){return s==='trialing'?'trialing':s==='active'?'active':s==='past_due'?'past_due':s==='unpaid'?'unpaid':s==='canceled'?'cancelled':null}
async function updateTenant(subscriptionId,patch){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error('Supabase server configuration missing');if(!subscriptionId)return;const r=await fetch(SUPABASE_URL+'/rest/v1/business_software_subscriptions?stripe_subscription_id=eq.'+encodeURIComponent(subscriptionId),{method:'PATCH',headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(patch)});if(!r.ok)throw new Error('Tenant billing update failed: '+await r.text())}
async function subscriptionChanged(s){const patch={current_period_end:s.current_period_end?new Date(s.current_period_end*1000).toISOString():null},status=stripeStatus(s.status);if(status)patch.billing_status=status;await updateTenant(s.id,patch)}
async function invoiceChanged(i,paid){const sub=typeof i.subscription==='string'?i.subscription:null;if(sub)await updateTenant(sub,{billing_status:paid?'active':'past_due'})}
export async function POST(req){const raw=await req.text();if(!verify(raw,req.headers.get('stripe-signature')))return new NextResponse('Invalid signature',{status:400});try{const event=JSON.parse(raw);if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded')await upsertSession(event.data.object);else if(event.type==='customer.subscription.updated'||event.type==='customer.subscription.deleted')await subscriptionChanged(event.data.object);else if(event.type==='invoice.paid')await invoiceChanged(event.data.object,true);else if(event.type==='invoice.payment_failed')await invoiceChanged(event.data.object,false);return NextResponse.json({received:true})}catch(e){console.error('stripe webhook',e);return new NextResponse('Webhook processing failed',{status:500})}}