import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {runtimeTenant} from "@/lib/business-software/runtime";
import {centralRest} from "@/lib/business-software/db";
const SB="https://iepqggrfenfqrqyzqyed.supabase.co",KEY="sb_publishable_ivTCLFGFroexc-3IHe25bg_qhzg_GIy";
async function userFor(tenantId:string){const jar=await cookies();const token=jar.get("bms_access_token")?.value;if(!token)return null;const u=await fetch(SB+"/auth/v1/user",{headers:{apikey:KEY,Authorization:"Bearer "+token},cache:"no-store"});if(!u.ok)return null;const auth=await u.json();const r=await centralRest("business_software_users?tenant_id=eq."+tenantId+"&auth_user_id=eq."+auth.id+"&status=eq.active&select=id,email,display_name,role,permissions&limit=1");const rows=await r.json();return rows[0]||null;}
async function ctx(){const tenant=await runtimeTenant();if(!tenant?.id)return null;const user=await userFor(tenant.id);return user?{tenant,user}:null;}
const esc=(v:string)=>encodeURIComponent(v);
async function event(tenant:string,task:string,user:string,type:string,detail:any={}){await centralRest("business_software_task_events",{method:"POST",body:JSON.stringify({tenant_id:tenant,task_id:task,actor_user_id:user,event_type:type,detail})});}
async function fullTask(tenant:string,id:string){const q=await centralRest("business_software_tasks?tenant_id=eq."+tenant+"&id=eq."+id+"&select=*");const t=(await q.json())[0];if(!t)return null;const [nr,er]=await Promise.all([centralRest("business_software_task_notes?tenant_id=eq."+tenant+"&task_id=eq."+id+"&select=*&order=created_at.asc"),centralRest("business_software_task_events?tenant_id=eq."+tenant+"&task_id=eq."+id+"&select=*&order=created_at.desc")]);return {...t,notes:await nr.json(),events:await er.json()};}
export async function GET(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorised"},{status:401});const u=new URL(req.url),id=u.searchParams.get("id");if(id)return NextResponse.json({task:await fullTask(c.tenant.id,id)});const [tr,ur,jr,pr]=await Promise.all([centralRest("business_software_tasks?tenant_id=eq."+c.tenant.id+"&select=*&order=created_at.desc"),centralRest("business_software_users?tenant_id=eq."+c.tenant.id+"&status=eq.active&select=id,email,display_name,role&order=display_name.asc"),centralRest("business_software_jobs?tenant_id=eq."+c.tenant.id+"&select=id,reference&order=created_at.desc&limit=250"),centralRest("business_software_task_preferences?tenant_id=eq."+c.tenant.id+"&user_id=eq."+c.user.id+"&select=*&limit=1")]);const rawTasks=await tr.json(),rawUsers=await ur.json(),rawJobs=await jr.json(),rawPrefs=await pr.json();const tasks=Array.isArray(rawTasks)?rawTasks:[],users=Array.isArray(rawUsers)?rawUsers:[],jobs=Array.isArray(rawJobs)?rawJobs:[],pref=(Array.isArray(rawPrefs)?rawPrefs:[])[0]||{email_reminders:false,daily_digest:false,in_app_reminders:true};return NextResponse.json({tasks,users,jobs,preferences:pref,currentUser:c.user},{headers:{"Cache-Control":"no-store"}});}
export async function POST(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorised"},{status:401});const b=await req.json(),action=String(b.action||"create");
if(action==="note"){if(!b.task_id||!String(b.body||"").trim())return NextResponse.json({error:"Note required"},{status:400});const r=await centralRest("business_software_task_notes",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({tenant_id:c.tenant.id,task_id:b.task_id,body:String(b.body).trim(),created_by_user_id:c.user.id})});if(!r.ok)return NextResponse.json({error:await r.text()},{status:400});await event(c.tenant.id,b.task_id,c.user.id,"note_added");return NextResponse.json({ok:true});}
if(action==="preferences"){const data={tenant_id:c.tenant.id,user_id:c.user.id,email_reminders:!!b.email_reminders,daily_digest:!!b.daily_digest,in_app_reminders:b.in_app_reminders!==false,updated_at:new Date().toISOString()};const r=await centralRest("business_software_task_preferences?on_conflict=tenant_id,user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(data)});return r.ok?NextResponse.json({ok:true}):NextResponse.json({error:await r.text()},{status:400});}
const title=String(b.title||"").trim();if(!title)return NextResponse.json({error:"Task title required"},{status:400});const data={tenant_id:c.tenant.id,title,description:String(b.description||"").trim()||null,status:b.status||"open",priority:b.priority||"normal",assignee_user_id:b.assignee_user_id||c.user.id,created_by_user_id:c.user.id,linked_job_id:b.linked_job_id||null,waiting_on:String(b.waiting_on||"").trim()||null,due_at:b.due_at||null,reminder_at:b.reminder_at||null,remind_in_app:b.remind_in_app!==false,remind_email:!!b.remind_email,recurrence:b.recurrence||"none"};const r=await centralRest("business_software_tasks",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(data)});if(!r.ok)return NextResponse.json({error:await r.text()},{status:400});const task=(await r.json())[0];await event(c.tenant.id,task.id,c.user.id,"created",{title});return NextResponse.json({task});}
export async function PATCH(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorised"},{status:401});const b=await req.json(),id=String(b.id||"");if(!id)return NextResponse.json({error:"Task required"},{status:400});const current=await fullTask(c.tenant.id,id);if(!current)return NextResponse.json({error:"Task not found"},{status:404});const allowed=["title","description","status","priority","assignee_user_id","linked_job_id","waiting_on","due_at","reminder_at","remind_in_app","remind_email","recurrence","completion_note","snoozed_until"];const data:any={updated_at:new Date().toISOString()};for(const k of allowed)if(k in b)data[k]=b[k]||(["remind_in_app","remind_email"].includes(k)?false:null);if(b.status==="completed"){data.completed_at=new Date().toISOString();data.archived_at=null;}if(b.status==="archived")data.archived_at=new Date().toISOString();if(b.status==="open"){data.completed_at=null;data.archived_at=null;}
const r=await centralRest("business_software_tasks?tenant_id=eq."+c.tenant.id+"&id=eq."+esc(id),{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(data)});if(!r.ok)return NextResponse.json({error:await r.text()},{status:400});await event(c.tenant.id,id,c.user.id,b.status==="completed"?"completed":b.status==="archived"?"archived":b.snoozed_until?"snoozed":"updated",data);
if(b.status==="completed"&&current.recurrence&&current.recurrence!=="none"&&current.due_at){const d=new Date(current.due_at);if(current.recurrence==="daily")d.setDate(d.getDate()+1);if(current.recurrence==="weekly")d.setDate(d.getDate()+7);if(current.recurrence==="monthly")d.setMonth(d.getMonth()+1);const nr=await centralRest("business_software_tasks",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({...current,id:undefined,notes:undefined,events:undefined,status:"open",completed_at:null,archived_at:null,created_at:undefined,updated_at:undefined,due_at:d.toISOString(),created_by_user_id:c.user.id})});if(nr.ok){const nt=(await nr.json())[0];await event(c.tenant.id,nt.id,c.user.id,"recurrence_created",{from:id});}}
return NextResponse.json({ok:true});}
export async function DELETE(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorised"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Task required"},{status:400});const r=await centralRest("business_software_tasks?tenant_id=eq."+c.tenant.id+"&id=eq."+esc(id),{method:"DELETE"});return r.ok?NextResponse.json({ok:true}):NextResponse.json({error:await r.text()},{status:400});}