'use client';
import {useEffect,useState} from 'react'; import DiamantCredit from '../../components/admin/DiamantCredit'; import '../zmanim.css'; import {sunset,tzeis85,candleOffset,formatTime} from '../../lib/zmanim';
const KEY='ds-zmanim-location';
function nextFriday(){const d=new Date();d.setHours(12,0,0,0);const add=(5-d.getDay()+7)%7;d.setDate(d.getDate()+add);return d}
export default function Shabbos(){
 const [loc,setLoc]=useState(null),[place,setPlace]=useState(''),[parasha,setParasha]=useState(null),[err,setErr]=useState(''),[week,setWeek]=useState(0); const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
 async function nameLoc(v){try{const r=await fetch(`/api/zmanim/location?lat=${v.lat}&lon=${v.lon}`),j=await r.json();setPlace(j.name||'')}catch{}} function ask(){setErr('');navigator.geolocation.getCurrentPosition(p=>{const v={lat:p.coords.latitude,lon:p.coords.longitude};localStorage.setItem(KEY,JSON.stringify(v));setLoc(v);nameLoc(v)},()=>setErr('Please allow location access to calculate times for your area.'),{enableHighAccuracy:true,timeout:10000})}
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.lat){setLoc(v);nameLoc(v)}else ask()}catch{ask()}},[]);
 const fri=nextFriday();fri.setDate(fri.getDate()+week*7);const sat=new Date(fri);sat.setDate(fri.getDate()+1); const heb=new Intl.DateTimeFormat('en-u-ca-hebrew',{day:'numeric',month:'long',year:'numeric'}).format(sat); useEffect(()=>{const y=sat.getFullYear(),m=sat.getMonth()+1,d=sat.getDate();fetch(`https://www.hebcal.com/hebcal?cfg=json&v=1&year=${y}&month=${m}&maj=on&s=on&lg=s`).then(r=>r.json()).then(j=>{const ds=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const e=(j.items||[]).find(x=>x.date===ds&&x.category==='parashat');if(!e){setParasha(null);return}const en=e.title.replace(/^Parashat /,'');fetch(`https://www.hebcal.com/hebcal?cfg=json&v=1&year=${y}&month=${m}&maj=on&s=on&lg=he`).then(r=>r.json()).then(h=>{const he=(h.items||[]).find(x=>x.date===ds&&x.category==='parashat');setParasha({en,he:he?.title?.replace(/^פרשת /,'')||''})})}).catch(()=>setParasha(null))},[week]);
 let ss,cl,out,off;if(loc){ss=sunset(new Date(Date.UTC(fri.getFullYear(),fri.getMonth(),fri.getDate(),12)),loc.lat,loc.lon);off=candleOffset(loc.lat,loc.lon);cl=ss?new Date(ss.getTime()-off*60000):null;out=tzeis85(new Date(Date.UTC(sat.getFullYear(),sat.getMonth(),sat.getDate(),12)),loc.lat,loc.lon)}
 const fmt=d=>new Intl.DateTimeFormat('en-GB',{timeZone:tz,weekday:'short',day:'numeric',month:'short'}).format(d);
 return <><div className="zpowered"><DiamantCredit compact/></div><main className="zpage"><section className="zcard"><h1 className="ztitle ztitleLong">Shabbos & Yom Tov Times</h1><div className="zdate">{fmt(fri)} – {fmt(sat)}</div><div className="zhebrew">{heb}</div>{parasha&&<div className="zparasha">Parashas {parasha.en}<div className="zparashaHeb">פרשת {parasha.he}</div></div>}{loc?<><div className="zrows"><div className="zrow"><span>Candle lighting</span><strong>{formatTime(cl,tz)}</strong></div><div className="zrow"><span>Shkiah</span><strong>{formatTime(ss,tz)}</strong></div><div className="zrow"><span>Shabbos ends*</span><strong>{formatTime(out,tz)}</strong></div></div><div className="zlocation">📍 <span className="zplace">{place||`${loc.lat.toFixed(3)}, ${loc.lon.toFixed(3)}`}</span> <button className="zbtn secondary" onClick={ask}>Update</button></div><p className="znote">Candle lighting is shown {off} minutes before sunset based on the recognised local convention where supported; otherwise 18 minutes. *Ending time shown at 8.5° below the horizon. Customs vary, so follow your community/Rav where different.</p></>:<button className="zbtn" onClick={ask}>Use my location</button>}{err&&<p className="zerror">{err}</p>}<div className="znav"><button className="zbtn secondary" onClick={()=>setWeek(x=>x-1)}>← Previous</button><button className="zbtn secondary" onClick={()=>setWeek(0)}>This week</button><button className="zbtn secondary" onClick={()=>setWeek(x=>x+1)}>Next →</button></div><div className="zlinks"><a href="/shkiah">Today's Shkiah →</a></div></section></main><footer className="zfooter"><DiamantCredit dark/></footer></>
}