'use client';
import {useEffect} from 'react';

const BOOK_URLS={
  single:'https://book.stripe.com/cNibJ2flLaXrgP1bka1Nu0l',
  three:'https://book.stripe.com/4gM5kEa1r7LffKX4VM1Nu0m',
  six:'https://book.stripe.com/5kQaEY7TjaXr2Yb0Fw1Nu0n'
};
const support=[
  ['Business direction and difficult decisions','Work through the decisions that are slowing progress and get clear on the most practical route forward.'],
  ['Prioritising an overwhelming task list','Separate what matters now from what can wait, then turn priorities into a realistic action plan.'],
  ['Pricing and profitability','Review pricing, margins and commercial decisions with a practical focus on stronger profitability.'],
  ['Business systems and processes','Improve how work moves through the business so fewer things rely on memory, chasing or firefighting.'],
  ['Client journeys and operational improvements','Identify friction in the customer experience and tighten the operational steps behind it.'],
  ['Accountability and implementation','Agree clear next actions, follow through on them and keep important work moving.'],
  ['Digital, website and automation opportunities','Spot sensible opportunities to use websites, systems or automation where they can genuinely save time or improve results.']
];
const whatsappSupport='Occasional brief WhatsApp support between sessions is included, helping you stay on track and keep your business moving';
const packages=[
  {key:'single',label:'SINGLE SESSION',title:'Single Session',price:'£300',bullets:['Approximately 50-60 minutes','Focused one-to-one Business Advisory'],button:'Book Single Session'},
  {key:'three',label:'3-SESSION PACKAGE',title:'3-Session Package',price:'£850',saving:'Save £50',bullets:['Three approximately 50-60 minute sessions','Suitable for working through a defined set of priorities with accountability between sessions',whatsappSupport],button:'Book 3 Sessions',featured:true},
  {key:'six',label:'6-SESSION PACKAGE',title:'6-Session Package',price:'£1,650',saving:'Save £150',bullets:['Six approximately 50-60 minute sessions','Best for sustained implementation, accountability and follow-through over a longer period',whatsappSupport],button:'Book 6 Sessions'}
];

function Logo({white=false}){return <img src={white?'/DS Logo with new tagline White.png':'/DS Logo latest tagline.png'} alt="Diamant Solutions" className={white?'footerOfficialLogo':'headerOfficialLogo'}/>}
function Icon({type}){const paths={email:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></>,phone:<><path d="M6.6 3.8 9 8.4 6.8 10a15.5 15.5 0 0 0 7.2 7.2l1.6-2.2 4.6 2.4c.6.3.9 1 .7 1.7-.5 1.8-2.2 3-4 2.9C9.1 21.4 2.6 14.9 2 7.1c-.1-1.8 1.1-3.5 2.9-4 .7-.2 1.4.1 1.7.7Z"/></>,office:<><path d="M12 22s7-6.1 7-13a7 7 0 1 0-14 0c0 6.9 7 13 7 13Z"/><circle cx="12" cy="9" r="2.5"/></>,company:<><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 7h3M13 7h3M8 11h3M13 11h3M8 15h3M13 15h3M10 21v-3h4v3"/></>};return <span className="contactIcon"><svg viewBox="0 0 24 24">{paths[type]}</svg></span>}
function Strip(){const set=<div className="advisoryStripSet"><span>Clear decisions</span><b>•</b><span>Practical action</span><b>•</b><span>Accountability</span><b>•</b><span>Implementation</span><b>•</b></div>;return <div className="advisoryStrip"><div className="advisoryStripTrack">{set}{set}</div></div>}

export default function AdvisoryClient(){
  useEffect(()=>{const els=[...document.querySelectorAll('.revealAdvisory')];const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');io.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -35px'});els.forEach(el=>io.observe(el));return()=>io.disconnect()},[]);

  return <main className="advisoryPage">
    <header className="advisoryHeader">
      <a className="headerBrand" href="/"><Logo/></a>
      <nav><a href="#support">HOW I CAN HELP</a><a href="#book">PRICING</a><a href="/websites">WEBSITES</a><a href="/software">BUSINESS SOFTWARE</a><a href="#contact">CONTACT</a></nav>
      <details className="mobileMenu"><summary aria-label="Open menu"><span/></summary><div><a href="#support">HOW I CAN HELP</a><a href="#book">PRICING</a><a href="/websites">WEBSITES</a><a href="/software">BUSINESS SOFTWARE</a><a href="#contact">CONTACT</a></div></details>
    </header>

    <section className="advisoryHero">
      <div className="advisoryHeroCopy revealAdvisory fromLeft"><p className="advisoryKicker">BUSINESS ADVISORY</p><h1>Less talking about what needs doing.<span>More getting it done.</span></h1><p className="advisoryHeroLead">Practical one-to-one support for business owners who need help making decisions, setting priorities and actually implementing them.</p><div className="advisoryActions"><a className="blueBtn" href="#book">Book a Session</a><a className="advisorySecondary" href="#support">See how I can help</a></div></div>
      <div className="decisionOrbit revealAdvisory fromRight" aria-hidden="true"><div className="orbitRing one"/><div className="orbitRing two"/><div className="orbitRing three"/><div className="orbitCore"><div><b>Decide.</b><small>THEN IMPLEMENT.</small></div></div><div className="orbitNode n1">Direction</div><div className="orbitNode n2">Profitability</div><div className="orbitNode n3">Systems</div><div className="orbitNode n4">Accountability</div></div>
    </section>

    <Strip/>
    <section id="support" className="advisorySection"><div className="advisorySectionHead revealAdvisory"><p className="advisoryKicker">PRACTICAL SUPPORT</p><h2>Work on the things that actually move the business forward.</h2><p>Sessions focus on the real decisions, bottlenecks and priorities in your business, not a generic coaching framework.</p></div><div className="supportGrid">{support.map((item,i)=><article key={item[0]} className={'supportCard revealAdvisory '+(i%2?'fromRight':'fromLeft')}><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></section>
    <section className="tailored"><div className="tailoredInner"><div className="revealAdvisory fromLeft"><p className="advisoryKicker">TAILORED TO YOUR BUSINESS</p><h2>No fixed programme. No generic formula.</h2></div><div className="tailoredCopy revealAdvisory fromRight"><p>Every business is different. The session is shaped around what is creating pressure, slowing progress or needs a decision now.</p><p>The aim is simple: understand the issue, make the decision, agree the next action and make sure it actually gets implemented.</p><div className="actionSteps"><div className="actionStep"><span>Understand</span></div><div className="actionStep"><span>Decide</span></div><div className="actionStep"><span>Act</span></div><div className="actionStep"><span>Follow through</span></div></div></div></div></section>
    <section className="aboutYehuda"><div className="revealAdvisory fromLeft" style={{position:'relative'}}><div className="yehudaAccent"/><div className="yehudaFrame"><img src="https://res.cloudinary.com/ds3zepqin/image/upload/e_upscale,q_100/v1789559192/diamant-solutions/mark-diamant-headshot.jpg" alt="Mark Diamant"/></div></div><div className="aboutYehudaCopy revealAdvisory fromRight"><p className="advisoryKicker">ABOUT ME</p><h2>Practical experience, not just theory.</h2><p>I’m an entrepreneur and director of multiple businesses, with hands-on experience launching, running and developing businesses and digital projects. I’m also actively involved in community organisations and previously spent seven years providing Business Advisory through Mesila, including delivering business talks and webinars.</p><p>My approach is practical: understand the issue, make a decision, agree the next action and make sure it actually gets implemented.</p></div></section>

    <section id="book" className="advisoryPrice"><div className="advisorySectionHead revealAdvisory"><p className="advisoryKicker">BUSINESS ADVISORY PRICING</p><h2>Choose the level of support that fits your business.</h2><p>Each session is tailored to your business and focused on practical decisions, implementation and follow-through.</p></div><div className="advisoryPriceGrid">{packages.map((pkg,i)=><article key={pkg.key} className={'advisoryPriceCard revealAdvisory '+(pkg.featured?'featured ':'')+(i===0?'fromLeft':i===2?'fromRight':'')}>{pkg.saving&&<div className="packageSaving">{pkg.saving}</div>}<small>{pkg.label}</small><h3>{pkg.title}</h3><div className="price">{pkg.price}</div><ul>{pkg.bullets.map(item=><li key={item}>{item}</li>)}</ul><a className="blueBtn bookButton" href={BOOK_URLS[pkg.key]}>{pkg.button}</a></article>)}</div><div className="bookingProcess revealAdvisory"><p><b>After booking, we’ll contact you by email or WhatsApp to arrange a date and time for your session(s) that works for you.</b></p><p>For multi-session packages, sessions can be arranged individually and do not need to be booked all at once.</p></div></section>

    <section id="contact" className="contact advisoryContact"><div className="revealAdvisory fromLeft"><p className="advisoryKicker">GET IN TOUCH</p><h2>Want to talk it through?</h2><p className="advisoryContactLead">If you have a question about Business Advisory, want to check whether it is the right fit, or simply prefer to speak before booking, get in touch.</p><div className="contactCards"><a href="mailto:info@diamantsolutions.co.uk"><b><Icon type="email"/>Email</b><span>info@diamantsolutions.co.uk</span></a><a href="https://wa.me/442032845074"><b><Icon type="phone"/>Phone & WhatsApp</b><span>0203 284 5074</span></a><div><b><Icon type="office"/>Office</b><span>Office 6, 1st Floor, Sutherland House<br/>70-78 West Hendon Broadway<br/>London, NW9 7BT</span></div><div><b><Icon type="company"/>Company</b><span>Diamant Solutions Ltd<br/>Company No. 16897347</span></div></div></div><form className="revealAdvisory fromRight" action="mailto:info@diamantsolutions.co.uk"><input placeholder="First name*"/><input placeholder="Last name*"/><input placeholder="Business name"/><input placeholder="Phone / WhatsApp"/><input type="email" placeholder="Email*"/><textarea placeholder="What would you like help with?*"/><button className="blueBtn">Submit Enquiry</button></form></section>
    <footer className="advisoryFooter"><Logo white/><div><b>Diamant Solutions Ltd</b><br/>Websites • Business Software • Direction<br/><br/>Office 6, 1st Floor, Sutherland House, 70-78 West Hendon Broadway, NW9 7BT</div><div><b>Contact</b><br/>info@diamantsolutions.co.uk<br/>0203 284 5074</div><div><b>Explore</b><br/><a href="/websites">Websites</a><br/><a href="/software">Business Software</a><br/><a href="/advisory">Business Advisory</a><br/><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></div></footer>
  </main>;
}