export const metadata={title:'Privacy Policy | Diamant Solutions'};

const sections=[
['1. Who We Are',<><p>Diamant Solutions Ltd, Company No. 16897347, London, UK. Email: info@diamantsolutions.co.uk.</p><p>We provide website design and development, custom CRM systems, hosting, ongoing support, business systems, technology solutions and related consultancy services.</p></>],
['2. Information We Collect',<p>We may collect your name, email address, phone number, company name, enquiry details, billing information and documents or data you voluntarily share for project work.</p>],
['3. How We Use Your Information',<p>We use information to respond to enquiries, provide quotes, deliver services, administer subscriptions and payments, communicate about projects, maintain client records and improve our services.</p>],
['4. Legal Basis',<p>We process personal data where necessary for a contract, our legitimate interests, legal obligations, or where you have given consent.</p>],
['5. Client CRM and Hosted Business Data',<><p>Where we build or host a CRM or other business system for a client, that system may contain personal data belonging to the client, including information about their customers, leads, staff, jobs, enquiries, files or other business records.</p><p>In those circumstances, the client is generally responsible for deciding why and how that data is collected and used. Where Diamant Solutions processes that data only to host, support or operate the client’s system, we act on the client’s instructions for the purpose of providing the agreed service. Clients are responsible for ensuring that the data they place in their CRM or business system is collected and used lawfully.</p><p>We do not use client CRM data for unrelated marketing or sell that data. Access is limited to what is reasonably required to provide, secure, troubleshoot or support the service.</p></>],
['6. Payments and Service Providers',<p>Payments and subscriptions may be processed by Stripe. We may also use reputable service providers for hosting, databases, storage, email, analytics and business administration. Those providers may process data on our behalf according to their own terms and applicable law.</p>],
['7. Cookies & Analytics',<p>Our website may use basic analytics and essential technologies required to operate the site. You can control non-essential cookies through your browser where applicable.</p>],
['8. Data Storage & Security',<p>We take reasonable technical and organisational steps to keep information secure and retain it only for as long as necessary for the relevant purpose, the provision of the service and legal obligations. Where a client leaves a hosted CRM service, we can provide a reasonable export of customer-owned CRM data where technically available, subject to the applicable service terms.</p>],
['9. Your Rights',<p>You may have rights to access, correct, delete or restrict use of your personal data, object to processing, and withdraw consent where applicable. Contact info@diamantsolutions.co.uk. If your information is held inside a CRM operated by one of our clients, you should normally contact that business directly because they control how that information is used.</p>],
['10. Contact',<p>For privacy questions, email <a href="mailto:info@diamantsolutions.co.uk">info@diamantsolutions.co.uk</a>.</p>]
];

export default function Privacy(){return <main><style>{`
.legalHeader{height:92px;display:flex;align-items:center;justify-content:space-between;padding:0 5vw;background:#fff;border-bottom:1px solid #e6edf4;position:relative;z-index:50}.legalHeader .headerBrand{height:62px;width:235px;max-width:32vw;overflow:visible;display:flex;align-items:center}.legalHeader .headerOfficialLogo{display:block;width:235px;height:auto}.footerOfficialLogo{display:block;width:auto;height:120px;max-width:480px;object-fit:contain}.legalHeader .headerBrand{flex:none} .legalHeader nav{display:flex;align-items:center;gap:0;overflow:visible;padding:14px 4px} .legalHeader nav a{position:relative;isolation:isolate;overflow:hidden;padding:11px 15px!important;border-radius:11px;color:#0b1725!important;transition:color 1.8s ease,transform .5s ease,box-shadow .5s ease} .legalHeader nav a+ a{margin-left:8px} .legalHeader nav a+ a{box-shadow:-8px 0 0 -7px rgba(151,171,194,.55)} .legalHeader nav a+ a::after{display:none!important} .legalHeader nav a::before{content:"";position:absolute;z-index:-1;left:-130%;top:-300%;width:360%;height:700%;border-radius:46%;background:conic-gradient(from 0deg,#5f91c8 0deg,#79a8dc 70deg,#3f78b3 145deg,#285f97 220deg,#6f9fd3 295deg,#5f91c8 360deg);opacity:0;transform:rotate(0deg) scale(.72);transition:opacity 2.6s ease,transform 2.6s ease} .legalHeader nav a:hover{color:#fff!important;transform:translateY(-1px);box-shadow:0 8px 22px rgba(50,92,145,.18)} .legalHeader nav a:hover::before{opacity:.94;transform:rotate(55deg) scale(1);animation:navSwirl 11s linear infinite}@keyframes navSwirl{from{transform:rotate(55deg) scale(.72)}to{transform:rotate(415deg) scale(1)}}.legalHeader .mobileMenu{display:none}.legalHeader .mobileMenu summary{list-style:none}.legalHeader .mobileMenu summary::-webkit-details-marker{display:none}
.legalHero{position:relative;overflow:hidden;padding:90px 6vw 72px;background:linear-gradient(135deg,#f8fbfe,#edf5fb)}.legalHero:before{content:'';position:absolute;inset:0;background:url('https://static.wixstatic.com/media/a9abeb_c77f2ebd8d1f47fab550bc4bce409664~mv2.png') center/cover;opacity:.08}.legalHero>div{position:relative;z-index:1;max-width:900px;margin:auto;text-align:center}.legalHero .eyebrow{font-size:12px;letter-spacing:2.7px;color:#4c80b8;font-weight:800;margin:0 0 14px}.legalHero h1{font-size:clamp(44px,5vw,70px);letter-spacing:-2.5px;line-height:1;margin:0;color:#111}.legalHero .updated{margin:18px 0 0;color:#748399;font-size:14px}.legalBody{padding:72px 6vw 90px;background:#fff}.legalWrap{max-width:940px;margin:auto;display:grid;gap:18px}.legalCard{background:#fff;border:1px solid #e2eaf2;border-radius:22px;padding:30px 34px;box-shadow:0 12px 32px #1738590b}.legalCard h2{font-size:22px;letter-spacing:-.4px;margin:0 0 12px;color:#17385f}.legalCard p{margin:8px 0;line-height:1.75;color:#56667b;font-size:15px}.legalCard a{color:#4c80b8;font-weight:700}.legalFooter{background:#102a4a;color:#d8e4f0;padding:38px 5vw;display:grid;grid-template-columns:1.25fr 1.25fr .8fr .9fr;gap:28px;align-items:start;font-size:13px;line-height:1.7}.legalFooter img{width:235px;height:auto;display:block}.legalFooter a{color:#fff}.legalFooter b{color:#fff}.legalFooter .links{text-align:left}
@media(max-width:800px){.legalHeader{height:78px;padding:0 14px}.legalHeader img{width:220px}.legalHeader nav{display:none}.legalHero{padding:62px 20px 50px}.legalBody{padding:46px 16px 60px}.legalWrap{gap:14px}.legalCard{padding:24px 20px;border-radius:18px}.legalCard h2{font-size:20px}.legalFooter{grid-template-columns:1fr;text-align:center;padding:26px 18px;gap:10px}.legalFooter img{width:270px;margin:auto}.legalFooter .links{text-align:center}}
footer{background:#102a4a;color:#d8e4f0;padding:38px 5vw;display:grid;grid-template-columns:1.25fr 1.25fr .8fr .9fr;gap:28px;align-items:start;font-size:13px;line-height:1.7}footer a{color:#fff}footer b{color:#fff}.footerOfficialLogo{display:block;width:auto;height:120px;max-width:480px;object-fit:contain}@media(max-width:800px){.legalHeader{height:82px!important;padding:0 12px!important}.legalHeader nav{display:none}footer{grid-template-columns:1fr!important;text-align:center;padding:28px 18px!important;gap:12px!important}.footerOfficialLogo{height:70px!important;max-width:300px!important;margin:auto}}
.legalHeader .mobileMenu{display:none}.legalHeader .mobileMenu summary{list-style:none}.legalHeader .mobileMenu summary::-webkit-details-marker{display:none}@media(max-width:800px){.legalHeader .mobileMenu{display:block;position:relative;z-index:70}.legalHeader .mobileMenu summary{width:43px;height:43px;border:1px solid #dce6f0;border-radius:11px;display:grid;place-items:center;cursor:pointer;background:#fff}.legalHeader .hamburger,.legalHeader .hamburger:before,.legalHeader .hamburger:after{width:21px;height:2px;background:#17385f;display:block;content:"";position:relative}.legalHeader .hamburger:before{position:absolute;top:-7px}.legalHeader .hamburger:after{position:absolute;top:7px}.legalHeader .mobileMenu div{position:absolute;right:0;top:51px;width:220px;background:#fff;border-radius:14px;box-shadow:0 18px 45px #102d5430;padding:10px;text-align:left}.legalHeader .mobileMenu a{display:block;padding:13px 14px;font-size:12px;font-weight:800;border-bottom:1px solid #edf2f7}.legalHeader .mobileMenu a:last-child{border:0}}@media(max-width:1024px){.legalHeader nav{display:none!important}.legalHeader .mobileMenu{display:block!important;position:relative!important;z-index:70!important}}
`}</style>
<header className="legalHeader"><a className="headerBrand" href="/"><img className="headerOfficialLogo" src="/DS Logo latest tagline.png" alt="Diamant Solutions"/></a><nav><a href="/">HOME</a><a href="/websites">WEBSITES</a><a href="/software">BUSINESS SOFTWARE</a><a href="/advisory">BUSINESS ADVISORY</a><a href="/#contact">CONTACT</a></nav><details className="mobileMenu"><summary aria-label="Open menu"><span className="hamburger"/></summary><div><a href="/">HOME</a><a href="/websites">WEBSITES</a><a href="/software">BUSINESS SOFTWARE</a><a href="/advisory">BUSINESS ADVISORY</a><a href="/#contact">CONTACT</a></div></details></header>
<section className="legalHero"><div><p className="eyebrow">PRIVACY</p><h1>Privacy Policy</h1><p className="updated">Last updated September 2026</p></div></section>
<section className="legalBody"><div className="legalWrap">{sections.map(([title,body])=><article className="legalCard" key={title}><h2>{title}</h2>{body}</article>)}</div></section>
<footer><img className="footerOfficialLogo" src="/DS Logo with new tagline White.png" alt="Diamant Solutions"/><div><b>Diamant Solutions Ltd</b><br/>Websites • Business Software • Direction<br/><br/>Office 6, 1st Floor, Sutherland House, 70-78 West Hendon Broadway, NW9 7BT</div><div><b>Contact</b><br/>info@diamantsolutions.co.uk<br/>0203 284 5074</div><div><b>Explore</b><br/><a href="/">Home</a><br/><a href="/websites">Websites</a><br/><a href="/software">Business Software</a><br/><a href="/advisory">Business Advisory</a><br/><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></div></footer>
</main>}
