export const metadata={title:'Privacy Policy | Diamant Solutions'};

const sections=[
['1. Who We Are',<><p>Diamant Solutions Ltd, Company No. 16897347, London, UK. Email: info@diamantsolutions.co.uk.</p><p>We provide website design and development, hosting, maintenance, ongoing support, business systems, technology solutions and related consultancy services.</p></>],
['2. Information We Collect',<p>We may collect your name, email address, phone number, company name, enquiry details, billing information and documents or data you voluntarily share for project work.</p>],
['3. How We Use Your Information',<p>We use information to respond to enquiries, provide quotes, deliver services, administer subscriptions and payments, communicate about projects, maintain client records and improve our services.</p>],
['4. Legal Basis',<p>We process personal data where necessary for a contract, our legitimate interests, legal obligations, or where you have given consent.</p>],
['5. Payments and Service Providers',<p>Payments and subscriptions may be processed by Stripe. We may also use reputable service providers for hosting, email, analytics and business administration. Those providers process data according to their own privacy terms and applicable law.</p>],
['6. Cookies & Analytics',<p>Our website may use basic analytics and essential technologies required to operate the site. You can control non-essential cookies through your browser where applicable.</p>],
['7. Data Storage & Security',<p>We take reasonable technical and organisational steps to keep information secure and retain it only for as long as necessary for the relevant purpose and legal obligations.</p>],
['8. Your Rights',<p>You may have rights to access, correct, delete or restrict use of your personal data, object to processing, and withdraw consent where applicable. Contact info@diamantsolutions.co.uk.</p>],
['9. Contact',<p>For privacy questions, email <a href="mailto:info@diamantsolutions.co.uk">info@diamantsolutions.co.uk</a>.</p>]
];

export default function Privacy(){return <main><style>{`
.legalHeader{height:86px;display:flex;align-items:center;justify-content:space-between;padding:0 5vw;border-bottom:1px solid #e5ebf2;background:#fff}.legalHeader img{width:250px;height:auto;display:block}.legalHeader nav{display:flex;gap:30px;font-size:12px;font-weight:800;letter-spacing:.7px}.legalHero{position:relative;overflow:hidden;padding:90px 6vw 72px;background:linear-gradient(135deg,#f8fbfe,#edf5fb)}.legalHero:before{content:'';position:absolute;inset:0;background:url('https://static.wixstatic.com/media/a9abeb_c77f2ebd8d1f47fab550bc4bce409664~mv2.png') center/cover;opacity:.08}.legalHero>div{position:relative;z-index:1;max-width:900px;margin:auto;text-align:center}.legalHero .eyebrow{font-size:12px;letter-spacing:2.7px;color:#4c80b8;font-weight:800;margin:0 0 14px}.legalHero h1{font-size:clamp(44px,5vw,70px);letter-spacing:-2.5px;line-height:1;margin:0;color:#111}.legalHero .updated{margin:18px 0 0;color:#748399;font-size:14px}.legalBody{padding:72px 6vw 90px;background:#fff}.legalWrap{max-width:940px;margin:auto;display:grid;gap:18px}.legalCard{background:#fff;border:1px solid #e2eaf2;border-radius:22px;padding:30px 34px;box-shadow:0 12px 32px #1738590b}.legalCard h2{font-size:22px;letter-spacing:-.4px;margin:0 0 12px;color:#17385f}.legalCard p{margin:8px 0;line-height:1.75;color:#56667b;font-size:15px}.legalCard a{color:#4c80b8;font-weight:700}.legalFooter{background:#102a4a;color:#d8e4f0;padding:34px 5vw;display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:24px;align-items:center;font-size:13px;line-height:1.6}.legalFooter img{width:255px;height:auto;display:block}.legalFooter a{color:#fff}.legalFooter .links{text-align:right}
@media(max-width:800px){.legalHeader{height:78px;padding:0 14px}.legalHeader img{width:220px}.legalHeader nav{display:none}.legalHero{padding:62px 20px 50px}.legalBody{padding:46px 16px 60px}.legalWrap{gap:14px}.legalCard{padding:24px 20px;border-radius:18px}.legalCard h2{font-size:20px}.legalFooter{grid-template-columns:1fr;text-align:center;padding:26px 18px;gap:10px}.legalFooter img{width:270px;margin:auto}.legalFooter .links{text-align:center}}
`}</style>
<header className="legalHeader"><a href="/"><img src="/DS Logo latest tagline.png" alt="Diamant Solutions"/></a><nav><a href="/">HOME</a><a href="/#process">HOW IT WORKS</a><a href="/#work">OUR WORK</a><a href="/#pricing">PRICING</a><a href="/#contact">CONTACT</a></nav></header>
<section className="legalHero"><div><p className="eyebrow">PRIVACY</p><h1>Privacy Policy</h1><p className="updated">Last updated August 2026</p></div></section>
<section className="legalBody"><div className="legalWrap">{sections.map(([title,body])=><article className="legalCard" key={title}><h2>{title}</h2>{body}</article>)}</div></section>
<footer className="legalFooter"><img src="/DS Logo with new tagline White.png" alt="Diamant Solutions"/><div>© 2026 Diamant Solutions Ltd.<br/>Company No. 16897347</div><div className="links"><a href="/terms">Terms of Service</a><br/><a href="/">Back to website</a></div></footer>
</main>}
