const MONTHLY='https://buy.stripe.com/5kQ28sc9z7Lf6an2NE1Nu00';
const ANNUAL='https://buy.stripe.com/4gM6oI8Xn7Lf9mz4VM1Nu01';

const work=[['Would Use Again','woulduseagain.com'],['M&J Metal','mjmetal.co.uk'],['Poll & See','pollandsee.com'],['Edible Print','edibleprint.uk']];
const testimonials=[
 ['Steve','Director, GenHome Capital Ltd','Customer application forms now auto-populate dozens of documents in seconds with perfect accuracy, allowing us to send quotes almost instantly.'],
 ['Yitzi Samet','Director, SamCerts Ltd','Professional service from start to finish. The website is clean, modern and exactly what we wanted. And delivered in under 24 hours!'],
 ['Esther','Director, Chocolate Smash Ltd','The product system Mark built pulls ingredients, weights, packaging, prices and profit calculations into one place. It works seamlessly across all our franchises.'],
 ['Yummi','Manager, Smooth Fulfilment Ltd','I used to spend 6 hours a week on invoicing. Now it takes 15 minutes, and half the team now produces four times the output thanks to the automation.']
];

export default function Home(){return <main>
<header><a className="brand" href="#top"><span className="diamond">◆</span><span>DIAMANT<br/><b>SOLUTIONS</b></span></a><nav><a href="#build">WHAT WE BUILD</a><a href="#pricing">PRICING</a><a href="/advisory">OWNER ADVISORY</a><a href="/investments">INVESTMENTS</a><a href="#contact">CONTACT</a></nav></header>
<section id="top" className="hero"><div className="orb one"/><div className="orb two"/><div className="heroCopy"><p className="eyebrow">WEBSITES • SYSTEMS • TECHNOLOGY</p><h1>Professional Websites<br/><span>That Help Businesses Grow</span></h1><p>From simple one-page websites to custom business platforms, we build fast, professional websites that generate enquiries & support your growth.</p><a className="btn" href="#pricing">Get Started</a></div><div className="heroArt"><div className="screen"><div className="screenTop"/><div className="screenBody"><i/><i/><i/></div></div><div className="phone"><div/><div/><div/></div></div></section>
<section id="build" className="section light"><p className="eyebrow">WHAT WE BUILD</p><h2>Technology that solves<br/>real business problems.</h2><p className="lead">Whether you need a simple website or a bespoke online platform, every project is built around your business, your customers and your long-term goals.</p><div className="cards"><article><b>01</b><h3>Websites</h3><p>Professional websites designed to build trust and generate enquiries.</p></article><article><b>02</b><h3>Bespoke Projects</h3><p>Customer portals, booking systems, business software, automation and more complex online solutions.</p></article><article><b>03</b><h3>AI & Technology</h3><p>Modern technology solutions that help businesses work smarter.</p></article></div></section>
<section className="section dark"><p className="eyebrow">HOW IT WORKS</p><h2>Simple from start to launch.</h2><div className="steps">{[['01','Free Discovery Call'],['02','Fixed Quote'],['03','Design & Build'],['04','Review'],['05','Launch'],['06','7-Day Grace Period']].map(x=><div key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3></div>)}</div></section>
<section className="statement"><h2>A professional website.<br/><span>Managed for the long term.</span></h2></section>
<section className="section light"><p className="eyebrow">WHY CHOOSE US</p><h2>Professional. Practical.<br/>Built to perform.</h2><div className="ticks">{['Bespoke, never template-based','Fast, secure and scalable','Built for desktop and mobile','Hosting included','Easy to expand as your business grows','Minor ongoing changes and support included'].map(t=><div key={t}>✓ {t}</div>)}</div></section>
<section className="section work"><p className="eyebrow">SOME OF OUR WORK</p><h2>Built for real businesses.</h2><div className="workGrid">{work.map(w=><a key={w[0]} href={'https://'+w[1]} target="_blank" rel="noreferrer"><span>{w[0]}</span><small>{w[1]} ↗</small></a>)}</div></section>
<section className="section light"><p className="eyebrow">ABOUT</p><h2>Practical technology.<br/>Long-term solutions.</h2><p className="lead">We build bespoke websites, software and online platforms for businesses looking for practical, long-term solutions. Alongside development, we also work with business owners through our dedicated Owner Advisory service and selectively partner on innovative projects and investment opportunities.</p></section>
<section id="pricing" className="section pricing"><p className="eyebrow">WEBSITE PRICING</p><h2>A professional website.<br/>Without the large upfront cost.</h2><p className="lead">Your website, hosting and minor ongoing changes are all included.</p><div className="priceWrap"><article className="price"><p>MONTHLY</p><h3>£29<span>/month</span></h3><ul><li>Professional business website</li><li>Mobile, tablet & desktop ready</li><li>Hosting included</li><li>Basic SEO setup</li><li>Minor ongoing changes & support</li><li>First draft typically within 24–48 hours</li></ul><a className="btn full" href={MONTHLY}>Get Started Monthly</a></article><article className="price featured"><div className="save">SAVE £49</div><p>ANNUAL</p><h3>£299<span>/year</span></h3><ul><li>Everything in the monthly plan</li><li>One simple annual payment</li><li>Professional managed website</li><li>Hosting included</li><li>Minor ongoing changes & support</li><li>Save £49 compared with monthly</li></ul><a className="btn full" href={ANNUAL}>Get Started Annually</a></article></div><p className="terms">*12-month minimum term. After that you can cancel anytime. Cancellation takes effect at the end of the paid/minimum period and the website goes offline when the subscription ends.</p><div className="complex"><h3>Need something more complex?</h3><p>For larger, bespoke or more complex projects, get in touch for a tailored quote.</p><a href="#contact">Discuss your project →</a></div></section>
<section className="section dark"><p className="eyebrow">TESTIMONIALS</p><h2>What our clients say.</h2><div className="quotes">{testimonials.map(t=><blockquote key={t[0]}><p>“{t[2]}”</p><footer><b>{t[0]}</b><span>{t[1]}</span></footer></blockquote>)}</div></section>
<section className="section beyond"><p className="eyebrow">BEYOND DEVELOPMENT</p><h2>Sometimes the right solution<br/>isn't a new website.</h2><div className="beyondGrid"><article><h3>Owner Advisory</h3><p>Practical guidance to help business owners improve structure, reduce pressure and make better decisions.</p><a href="/advisory">Explore Owner Advisory →</a></article><article><h3>Investments</h3><p>We selectively partner with businesses seeking investment, growth capital or strategic support.</p><a href="/investments">Explore Investments →</a></article></div></section>
<section id="contact" className="section contact"><div><p className="eyebrow">CONTACT INFO</p><h2>Let's talk about<br/>your business.</h2><p><b>Email</b><br/><a href="mailto:info@diamantsolutions.co.uk">info@diamantsolutions.co.uk</a></p><p><b>Phone & WhatsApp</b><br/><a href="https://wa.me/442032845074">0203 284 5074</a></p><p><b>Office</b><br/>Office 6, 1st Floor, Sutherland House,<br/>70–78 West Hendon Broadway,<br/>London, NW9 7BT, United Kingdom</p><p><b>Company</b><br/>Diamant Solutions Ltd (16897347)</p></div><form action="mailto:info@diamantsolutions.co.uk" method="post" encType="text/plain"><input name="firstName" placeholder="First name" required/><input name="lastName" placeholder="Last name" required/><input name="company" placeholder="Company"/><input name="phone" placeholder="Phone"/><input name="email" type="email" placeholder="Email" required/><textarea name="message" placeholder="Tell us about your project" required/><button className="btn">Submit</button></form></section>
<footer className="footer"><div className="brand"><span className="diamond">◆</span><span>DIAMANT <b>SOLUTIONS</b></span></div><p>Diamant Solutions Ltd · Company No. 16897347</p><p>© 2026 Diamant Solutions Ltd. All rights reserved. · <a href="/privacy">Privacy Policy</a> · <a href="/terms">Terms of Service</a></p></footer>
</main>}
