'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
const tenants=[
 {name:'Northstar Property',short:'NP',accent:'#315f8e',type:'PROPERTY MANAGEMENT',term:'Jobs',intro:'Properties, landlords, tenants, contractors, maintenance jobs, documents and payments.',rows:[['Oak House','Boiler repair','Contractor booked','£1,850'],['12 Finchley Road','Tenant inspection','Today','£420'],['Cedar Court','Maintenance quote','Awaiting approval','£2,640']]},
 {name:'BrightSpark Electrical',short:'BE',accent:'#d27832',type:'TRADES & CONTRACTORS',term:'Jobs',intro:'Enquiries, site visits, jobs, teams, quotes, materials, invoices and payments.',rows:[['ABC Property Ltd','Consumer unit upgrade','Site visit today','£2,450'],['John Smith','Garden lighting','Quote ready','£1,280'],['North London Estates','Rewire','Payment received','£6,250']]},
 {name:'Harbour Insurance',short:'HI',accent:'#377d68',type:'INSURANCE & BROKERAGE',term:'Cases',intro:'Clients, policies, renewals, follow-ups, documents, notes and payments.',rows:[['J Cohen Ltd','Commercial renewal','14 days','£3,200'],['Apex Retail','Policy documents','Requested','£980'],['Greenway Foods','Annual premium','Received','£4,750']]},
 {name:'Studio North',short:'SN',accent:'#7656a6',type:'CREATIVE AGENCY',term:'Projects',intro:'Clients, projects, tasks, approvals, files, quotes, invoices and deadlines.',rows:[['Acme Foods','Website refresh','Approval due','£2,800'],['Harper & Co','Brand project','Files received','£1,650'],['Northstar','Campaign','Invoice due Friday','£3,400']]}
];
const tabs=['Dashboard','Customers','Jobs','Quotes','Invoices','Payments','Files','Team'];
const tour=[
 {tab:'Dashboard',title:'Your day at a glance',copy:'See what needs attention, active work and money outstanding as soon as you sign in.'},
 {tab:'Customers',title:'Every customer in one place',copy:'Keep contact details, work history, documents and activity together.'},
 {tab:'Jobs',title:'Follow work from enquiry to completion',copy:'Use stages that match the way your business actually works.'},
 {tab:'Quotes',title:'Create and manage quotes',copy:'Prepare, review and keep track of quotes without losing the job context.'},
 {tab:'Invoices',title:'Stay on top of invoicing',copy:'See what has been invoiced, what is due and what still needs action.'},
 {tab:'Payments',title:'Know what has been paid',copy:'Track payments and outstanding balances alongside the work.'},
 {tab:'Files',title:'Keep the paperwork with the work',copy:'Photos, documents and other files stay attached to the right customer or job.'},
 {tab:'Team',title:'Give the right people the right access',copy:'Your team sees what they need without exposing everything to everyone.'}
];
function Activity({rows,term,query,setQuery}){return <div className="activityPanel"><div className="panelHead"><b>Recent {term.toLowerCase()}</b><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search..."/></div>{rows.map((r,i)=><button className="activityRow" key={r[0]+i}><span><b>{r[0]}</b><small>{r[1]}</small></span><span><em>{r[2]}</em><strong>{r[3]}</strong></span></button>)}{!rows.length&&<p className="empty">No matching records.</p>}</div>}
function Money(){return <aside className="moneyPanel"><b>Money overview</b><div><small>QUOTED</small><strong>£18,620</strong></div><div><small>INVOICED</small><strong>£14,200</strong></div><div><small>PAID</small><strong>£9,780</strong></div><div><small>OUTSTANDING</small><strong>£4,420</strong></div></aside>}
function Module({tab,term,rows,query,setQuery}){const labels={Customers:'customer',Jobs:term.slice(0,-1).toLowerCase(),Quotes:'quote',Invoices:'invoice',Payments:'payment',Files:'file',Team:'team member'};return <div className="modulePanel"><div className="moduleToolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Search '+tab.toLowerCase()+'...'}/><button>+ New {labels[tab]||'item'}</button></div><div className="moduleTable"><div className="tableHead"><span>{tab==='Customers'?'Customer':'Name'}</span><span>Details</span><span>Status</span><span>{['Files','Team'].includes(tab)?'Updated':'Value'}</span></div>{rows.map((r,i)=><button className="tableRow" key={r[0]+i}><span><b>{r[0]}</b></span><span>{r[1]}</span><span><em>{tab==='Customers'?'Active':r[2]}</em></span><span>{['Files','Team'].includes(tab)?(i+1)+'d ago':r[3]}</span></button>)}</div></div>}
function Demo({tenant,setTenant}){const [tab,setTab]=useState('Dashboard'),[tourStep,setTourStep]=useState(-1),[query,setQuery]=useState('');const timer=useRef(null),t=tenants[tenant];const shown=useMemo(()=>t.rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase())),[t,query]);const stop=()=>{setTourStep(-1);if(timer.current)clearTimeout(timer.current)};useEffect(()=>{if(tourStep<0)return;setTab(tour[tourStep].tab);timer.current=setTimeout(()=>setTourStep(s=>s>=tour.length-1?-1:s+1),6500);return()=>clearTimeout(timer.current)},[tourStep]);return <div className="realDemo" style={{'--tenant':t.accent}}><div className="demoChooser"><div><small>TRY A DIFFERENT SETUP</small><select value={tenant} onChange={e=>{stop();setTenant(Number(e.target.value));setTab('Dashboard')}}>{tenants.map((x,i)=><option value={i} key={x.name}>{x.name} · {x.type}</option>)}</select></div><button onClick={()=>tourStep<0?setTourStep(0):stop()}>{tourStep<0?'▶ Take the guided tour':'Exit tour'}</button></div><div className="productWindow"><div className="productHeader"><div className="tenantBrand"><b>{t.short}</b><span><strong>{t.name}</strong><small>Business Management Software</small></span></div><div className="productHeaderActions"><span>Settings</span><span>Logout</span><button>+ New {t.term.slice(0,-1)}</button></div></div><div className="productNav">{tabs.map(x=><button className={tab===x?'active':''} key={x} onClick={()=>{stop();setTab(x)}}>{x==='Jobs'?t.term:x}</button>)}</div><div className="productBody"><div className="productTitle"><div><small>{t.type}</small><h3>{tab==='Dashboard'?'Good morning. Here’s what needs attention.':tab+' at a glance'}</h3><p>{t.intro}</p></div><button>+ New</button></div>{tab==='Dashboard'?<><div className="statRow"><article><small>NEW ENQUIRIES</small><b>8</b><span>3 need action</span></article><article><small>ACTIVE {t.term.toUpperCase()}</small><b>24</b><span>6 due this week</span></article><article><small>QUOTES OUT</small><b>£12,840</b><span>5 awaiting reply</span></article><article><small>OUTSTANDING</small><b>£8,420</b><span>Payments due</span></article></div><div className="workArea"><Activity rows={shown} term={t.term} query={query} setQuery={setQuery}/><Money/></div></>:<Module tab={tab} term={t.term} rows={shown} query={query} setQuery={setQuery}/>}</div>{tourStep>=0&&<div className="tourCard"><div><small>GUIDED TOUR · {tourStep+1} OF {tour.length}</small><h4>{tour[tourStep].title}</h4><p>{tour[tourStep].copy}</p></div><div className="tourProgress"><i style={{width:(((tourStep+1)/tour.length)*100)+'%'}}/></div><div className="tourControls"><button disabled={tourStep===0} onClick={()=>setTourStep(s=>Math.max(0,s-1))}>Back</button><button onClick={()=>setTourStep(s=>s>=tour.length-1?-1:s+1)}>{tourStep===tour.length-1?'Finish':'Next'}</button></div></div>}</div></div>}

export default function SoftwareDemo(){const [tenant,setTenant]=useState(0);return <Demo tenant={tenant} setTenant={setTenant}/>}
