export const metadata={title:'Terms of Service | Diamant Solutions'};

const sections=[
['1. About These Terms',<p>These terms apply to services supplied by Diamant Solutions Ltd, Company No. 16897347. Any project-specific written quotation or agreement forms part of these terms and takes priority where it expressly differs.</p>],
['2. Managed Website Plan',<p>Our standard managed website service is available at £29 per month or £299 per year unless another price has been agreed in writing. The plan starts when the customer signs up and the first payment is taken immediately, before work begins. We then begin the website build. Our usual target is to provide the first draft within 24–48 hours, although this is a target rather than a guaranteed delivery time and may depend on the customer providing the information or materials we need.</p>],
['3. Minimum Term',<p>The managed website plan has a 12-month minimum term starting from the date the customer signs up. Monthly customers are committed to the first 12 monthly payments. Annual customers pay for the full 12-month period in advance when signing up.</p>],
['4. What Is Included',<p>The managed website plan includes the agreed website build, hosting while the subscription remains active, responsive optimisation, basic SEO setup and reasonable minor ongoing content or design changes. New functionality, substantial redesigns, additional pages or more complex development may be quoted separately.</p>],
['5. Cancellation',<p>After the minimum term, the subscription may be cancelled. Cancellation takes effect at the end of the applicable paid billing period. The managed website service and hosting end when the subscription ends and the website may then go offline.</p>],
['6. Website, Domain and Content',<p>The customer retains ownership of their domain name and materials they provide, including their branding, text, images and business data. The website design, development implementation and code supplied as part of the managed service remain part of the managed service unless an alternative ownership arrangement is agreed in writing.</p>],
['7. Payments',<p>Subscription payments are processed through Stripe. If a payment fails, we may retry payment, contact you and suspend or end the service if payment remains outstanding. Fees already paid for an annual billing period are not normally refunded simply because the customer chooses to stop using the service during that paid period, subject to any rights that cannot legally be excluded.</p>],
['8. Bespoke Projects',<p>Larger or more complex projects are quoted separately. The scope, price and payment terms for those projects will be confirmed before work begins.</p>],
['9. Customer Responsibilities',<p>You are responsible for providing accurate information and content, confirming that you have permission to use supplied materials and reviewing requested approvals or revisions in a reasonable time.</p>],
['10. Liability',<p>We will provide services with reasonable care and skill. Nothing in these terms excludes liability that cannot legally be excluded. To the extent permitted by law, we are not responsible for indirect or consequential losses or for failures caused by third-party services outside our reasonable control.</p>],
['11. Contact',<p>Questions about these terms can be sent to <a href="mailto:info@diamantsolutions.co.uk">info@diamantsolutions.co.uk</a>.</p>]
];

export default function Terms(){return <main><style>{`
.legalHeader{height:86px;display:flex;align-items:center;justify-content:space-between;padding:0 5vw;border-bottom:1px solid #e5ebf2;background:#fff}.legalHeader img{width:250px;height:auto;display:block}.legalHeader nav{display:flex;gap:30px;font-size:12px;font-weight:800;letter-spacing:.7px}.legalHero{position:relative;overflow:hidden;padding:90px 6vw 72px;background:linear-gradient(135deg,#f8fbfe,#edf5fb)}.legalHero:before{content:'';position:absolute;inset:0;background:url('https://static.wixstatic.com/media/a9abeb_c77f2ebd8d1f47fab550bc4bce409664~mv2.png') center/cover;opacity:.08}.legalHero>div{position:relative;z-index:1;max-width:900px;margin:auto;text-align:center}.legalHero .eyebrow{font-size:12px;letter-spacing:2.7px;color:#4c80b8;font-weight:800;margin:0 0 14px}.legalHero h1{font-size:clamp(44px,5vw,70px);letter-spacing:-2.5px;line-height:1;margin:0;color:#111}.legalHero .updated{margin:18px 0 0;color:#748399;font-size:14px}.legalBody{padding:72px 6vw 90px;background:#fff}.legalWrap{max-width:940px;margin:auto;display:grid;gap:18px}.legalCard{background:#fff;border:1px solid #e2eaf2;border-radius:22px;padding:30px 34px;box-shadow:0 12px 32px #1738590b}.legalCard h2{font-size:22px;letter-spacing:-.4px;margin:0 0 12px;color:#17385f}.legalCard p{margin:8px 0;line-height:1.75;color:#56667b;font-size:15px}.legalCard a{color:#4c80b8;font-weight:700}.legalFooter{background:#102a4a;color:#d8e4f0;padding:34px 5vw;display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:24px;align-items:center;font-size:13px;line-height:1.6}.legalFooter img{width:255px;height:auto;display:block}.legalFooter a{color:#fff}.legalFooter .links{text-align:right}
@media(max-width:800px){.legalHeader{height:78px;padding:0 14px}.legalHeader img{width:220px}.legalHeader nav{display:none}.legalHero{padding:62px 20px 50px}.legalBody{padding:46px 16px 60px}.legalWrap{gap:14px}.legalCard{padding:24px 20px;border-radius:18px}.legalCard h2{font-size:20px}.legalFooter{grid-template-columns:1fr;text-align:center;padding:26px 18px;gap:10px}.legalFooter img{width:270px;margin:auto}.legalFooter .links{text-align:center}}
`}</style>
<header className="legalHeader"><a href="/"><img src="/DS Logo latest tagline.png" alt="Diamant Solutions"/></a><nav><a href="/">HOME</a><a href="/#process">HOW IT WORKS</a><a href="/#work">OUR WORK</a><a href="/#pricing">PRICING</a><a href="/#contact">CONTACT</a></nav></header>
<section className="legalHero"><div><p className="eyebrow">TERMS</p><h1>Terms of Service</h1><p className="updated">Last updated August 2026</p></div></section>
<section className="legalBody"><div className="legalWrap">{sections.map(([title,body])=><article className="legalCard" key={title}><h2>{title}</h2>{body}</article>)}</div></section>
<footer className="legalFooter"><img src="/DS Logo with new tagline White.png" alt="Diamant Solutions"/><div>© 2026 Diamant Solutions Ltd.<br/>Company No. 16897347</div><div className="links"><a href="/privacy">Privacy Policy</a><br/><a href="/">Back to website</a></div></footer>
</main>}
