'use client';
import {useEffect,useMemo,useState} from 'react';import {ToolHeader,ToolFooter} from '../../components/ToolShell';import DatePicker from '../../components/DatePicker';import '../zmanim.css';import './yomi.css';import {jewishDateEnglish,jewishDateHebrew} from '../../lib/jewishDate';
const main=['Daf Yomi','Amud Yomi','Mishnah Yomi','Nach Yomi','Mishnah Berurah Yomi'],more=['Chofetz Chaim Yomi','Shemiras HaLashon','Rambam Yomi','Tehillim Yomi'];
const iso=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const fromIso=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const ordinal=n=>n+(n%100>=11&&n%100<=13?'th':({1:'st',2:'nd',3:'rd'}[n%10]||'th'));
const jewishDate=s=>{const m=String(s||'').match(/(\d+)\s+([^,]+),\s*(\d+)/);return m?ordinal(+m[1])+' of '+m[2]+', '+m[3]:s};
export default function Yomi(){const today=useMemo(()=>iso(new Date()),[]),[date,setDate]=useState(today),[data,setData]=useState(null),[err,setErr]=useState('');
 useEffect(()=>{setData(null);setErr('');fetch('/api/yomi?date='+date).then(r=>r.json()).then(j=>{setData(j);if(j.error)setErr(j.error)}).catch(()=>setErr('Daily learning is temporarily unavailable.'))},[date]);
 const d=fromIso(date),civil=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d),map=new Map((data?.items||[]).map(x=>[x.name,x]));
 const move=n=>{const x=fromIso(date);x.setDate(x.getDate()+n);setDate(iso(x))};
 const row=name=>{const x=map.get(name),body=<><span>{name}</span><strong>{x?.value||'Not available'}</strong>{x?.hebrew&&<small dir="rtl">{x.hebrew}</small>}{x?.url&&<em className="yomiOpen">Open today’s learning</em>}</>;return x?.url?<a key={name} className="yomiLearningLink" href={x.url} target="_blank" rel="noopener noreferrer"><article>{body}</article></a>:<article key={name}>{body}</article>};
 return <><ToolHeader/><main className="yomiPage"><section className="yomiCard"><h1>{date===today?'Yomi Today':'Daily Yomi'}</h1><p className="yomiIntro">Your daily learning, clearly in one place.</p><div className="yomiDates">{civil}<span>{jewishDateEnglish(d)} · <em className="yomiHebDate" dir="rtl">{jewishDateHebrew(d)}</em></span></div><div className="yomiNav"><button onClick={()=>move(-1)}>Previous</button><button className={date===today?'active':''} onClick={()=>setDate(today)}>Current</button><button onClick={()=>move(1)}>Next</button><DatePicker value={date} onChange={setDate}/></div>{!data&&!err&&<div className="yomiLoading">Loading daily learning…</div>}{err&&<div className="yomiError">{err}</div>}{data&&!err&&<><div className="yomiGrid">{main.map(row)}</div><h2>More daily learning</h2><div className="yomiGrid yomiMore">{more.map(row)}</div></>}</section></main><p className="yomiSource yomiSourceBottom">Daily learning schedules supplied by Hebcal.</p><ToolFooter/></>}