export const YAHRZEITS=[
{month:'Tishrei',day:25,name:'Rabbi Levi Yitzchak of Berditchev',he:'רבי לוי יצחק מברדיטשוב',years:'1740–1809',type:'Torah leader',blurb:'A major Chassidic leader, famed as the Berditchever Rav and as a passionate defender of the Jewish people. He authored Kedushas Levi.'},
{month:'Tishrei',day:25,name:'Rabbi Moshe Sofer — Chasam Sofer',he:'רבי משה סופר — החתם סופר',years:'1762–1839',type:'Torah leader',blurb:'Leading rabbi of Pressburg and one of the most influential halachic authorities of the modern era, known by the title of his responsa, Chasam Sofer.'},
{month:'Tishrei',day:26,name:'Rabbi Asher Perlov of Stolin',he:'רבי אשר מסטולין',years:'1760–1826',type:'Chassidic leader',blurb:'Son of Rabbi Aharon the Great of Karlin and an early leader of Karlin–Stolin Chassidus. He led and expanded the community from Stolin.'},
{month:'Tishrei',day:26,name:'Rabbi Aharon of Zhitomir',he:'רבי אהרן מז׳יטומיר',years:'d. 1816',type:'Chassidic leader',blurb:'A close disciple of Rabbi Levi Yitzchak of Berditchev. His teachings were preserved by his students in the sefer Toldos Aharon.'},
{month:'Tishrei',day:26,name:'Rabbi Yehuda Yudel Rosenberg',he:'רבי יהודה יודל רוזנברג',years:'1859–1935',type:'Rabbi & author',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/%D7%99%D7%95%D7%93%D7%9C_%D7%A8%D7%95%D7%96%D7%A0%D7%91%D7%A8%D7%92.jpg',blurb:'A Polish-born rabbi, dayan and prolific author who later served communities in Canada. His works ranged from halacha to popular Jewish literature.'},
{month:'Tishrei',day:27,name:'Rabbeinu Yitzchak ben Shmuel — Ri Hazaken',he:'רבינו יצחק בן שמואל — ר״י הזקן',years:'c. 1115–c. 1184',type:'Rishon',blurb:'One of the leading Baalei Tosafos and a grandson of Rashi through his mother. His teachings became foundational to the Tosafist tradition.'},
{month:'Tishrei',day:29,name:'Don Isaac Abarbanel',he:'דון יצחק אברבנאל',years:'1437–1508',type:'Torah scholar & statesman',blurb:'Biblical commentator, philosopher and statesman who served royal courts in Iberia and lived through the Spanish expulsion.'},
{month:'Tishrei',day:29,name:'Shimon HaTzaddik',he:'שמעון הצדיק',years:'Second Temple era',type:'Torah leader',blurb:'A leading figure of the early Second Temple period and one of the last members of the Anshei Knesses HaGedolah, remembered in Pirkei Avos.'}
,
{month:'Tammuz',day:11,name:'Alfred Dreyfus',he:'אלפרד דרייפוס',years:'1859–1935',type:'Jewish historical figure',blurb:'French army officer whose wrongful conviction for treason became the Dreyfus Affair, a defining episode in modern European Jewish history and the fight against antisemitism.'},
{month:'Tammuz',day:20,name:'Theodor Herzl',he:'בנימין זאב הרצל',years:'1860–1904',type:'Zionist leader',blurb:'Journalist, writer and founder of modern political Zionism. He convened the First Zionist Congress and became the movement’s central international figure.'},
{month:'Tammuz',day:29,name:'Ze’ev Jabotinsky',he:'זאב ז׳בוטינסקי',years:'1880–1940',type:'Zionist leader',blurb:'Writer, orator and Zionist leader who founded Revisionist Zionism and played a major role in Jewish self-defence and political organisation.'},
{month:'Kislev',day:6,name:'David Ben-Gurion',he:'דוד בן־גוריון',years:'1886–1973',type:'Israeli statesman',blurb:'Israel’s first prime minister and a principal leader in the establishment of the State of Israel, its early institutions and the absorption of mass immigration.'}
];