export const YAHRZEITS=[
{month:'Tishrei',day:25,name:'Rabbi Levi Yitzchak of Berditchev',he:'רבי לוי יצחק מברדיטשוב',years:'1740–1809',type:'Torah leader',blurb:'A major Chassidic leader, famed as the Berditchever Rav and as a passionate defender of the Jewish people. He authored Kedushas Levi.'},
{month:'Tishrei',day:25,name:'Rabbi Moshe Sofer — Chasam Sofer',he:'רבי משה סופר — החתם סופר',years:'1762–1839',type:'Torah leader',blurb:'Leading rabbi of Pressburg and one of the most influential halachic authorities of the modern era, known by the title of his responsa, Chasam Sofer.'},
{month:'Tishrei',day:26,name:'Rabbi Asher Perlov of Stolin',he:'רבי אשר מסטולין',years:'1760–1826',type:'Chassidic leader',blurb:'Son of Rabbi Aharon the Great of Karlin and an early leader of Karlin–Stolin Chassidus. He led and expanded the community from Stolin.'},
{month:'Tishrei',day:26,name:'Rabbi Aharon of Zhitomir',he:'רבי אהרן מז׳יטומיר',years:'d. 1816',type:'Chassidic leader',blurb:'A close disciple of Rabbi Levi Yitzchak of Berditchev. His teachings were preserved by his students in the sefer Toldos Aharon.'},
{month:'Tishrei',day:26,name:'Rabbi Yehuda Yudel Rosenberg',he:'רבי יהודה יודל רוזנברג',years:'1859–1935',type:'Rabbi & author',blurb:'A Polish-born rabbi, dayan and prolific author who later served communities in Canada. His works ranged from halacha to popular Jewish literature.'},
{month:'Tishrei',day:27,name:'Rabbeinu Yitzchak ben Shmuel — Ri Hazaken',he:'רבינו יצחק בן שמואל — ר״י הזקן',years:'c. 1115–c. 1184',type:'Rishon',blurb:'One of the leading Baalei Tosafos and a grandson of Rashi through his mother. His teachings became foundational to the Tosafist tradition.'},
{month:'Tishrei',day:29,name:'Don Isaac Abarbanel',he:'דון יצחק אברבנאל',years:'1437–1508',type:'Torah scholar & statesman',blurb:'Biblical commentator, philosopher and statesman who served royal courts in Iberia and lived through the Spanish expulsion.'},
{month:'Tishrei',day:29,name:'Shimon HaTzaddik',he:'שמעון הצדיק',years:'Second Temple era',type:'Torah leader',blurb:'A leading figure of the early Second Temple period and one of the last members of the Anshei Knesses HaGedolah, remembered in Pirkei Avos.'}
];