'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
import '../setup/setup.css';

const steps=[
 {title:'Your business',fields:[['businessName','Business name'],['contactName','Your name'],['email','Email address'],['phone','Phone number'],['existingWebsite','Existing website (if you have one)']]},
 {title:'What the website needs to do',fields:[['businessType','What does your business do?'],['services','What services or products should the website explain?'],['mainGoal','What is the main thing you want visitors to do?'],['audience','Who are your main customers?']]},
 {title:'Pages & content',fields:[['pages','Which pages do you need?'],['content','Do you already have wording/content, or would you like help shaping it?'],['contactDetails','What contact details should appear on the website?'],['socialLinks','Social media links, if any']]},
 {title:'Look & feel',fields:[['logo','Your logo'],['colours','Brand colours (if known)'],['examples','Any websites you like? Tell us what you like about them.'],['photos','What photos or images do you have available?']]},
 {title:'Domain & final details',fields:[['domain','Do you already own a domain? If yes, which one?'],['domainAccess','Who currently manages your domain or existing website?'],['features','Anything extra needed, such as forms, galleries, downloads or bookings?'],['anythingElse','Anything else we should know?']]}
];
const longKeys=['businessType','services','mainGoal','audience','pages','content','contactDetails','socialLinks','colours','examples','photos','domainAccess','features','anythingElse'];
export default function WebsiteSetupPage(){
 const [data,setData]=useState({}),[step,setStep]=useState(0),[saved,setSaved]=useState(false),[session,setSession]=useState(null),[tenantId,setTenantId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[logoPath,setLogoPath]=useState('');
 const pct=useMemo(()=>Math.round(((step+1)/steps.length)*100),[step]);const update=(k,v)=>setData(x=>({...x,[k]:v}));
 useEffect(()=>{try{const raw=localStorage.getItem('ds-website-onboarding');if(raw){const v=JSON.parse(raw);setData(v.data||{});setStep(Math.min(v.step||0,steps.length-1));}}catch{}supabase.auth.getSession().then(({data:{session:s}})=>setSession(s));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session?.user)return;setBusy(true);supabase.from('tenant_members').select('tenant_id').eq('user_id',session.user.id).limit(1).single().then(async({data:m,error})=>{if(error){setMessage('We could not load your website setup account. Please refresh and try again.');setBusy(false);return}setTenantId(m.tenant_id);const {data:o}=await supabase.from('onboarding').select('*').eq('tenant_id',m.tenant_id).single();if(o?.service_type==='website'){setData(x=>({...x,...(o.answers||{})}));setStep(Math.min(o.current_step||0,steps.length-1));setLogoPath(o.logo_path||'')}setBusy(false)});},[session?.user?.id]);
 useEffect(()=>{if(!Object.keys(data).length)return;const t=setTimeout(async()=>{try{localStorage.setItem('ds-website-onboarding',JSON.stringify({data,step,updatedAt:new Date().toISOString()}))}catch{}if(session&&tenantId){const {error}=await supabase.from('onboarding').update({service_type:'website',answers:data,current_step:step,progress:pct,status:'in_progress'}).eq('tenant_id',tenantId);if(error){setMessage('Your latest change is saved on this device, but could not be saved online.');return}}setSaved(true);setTimeout(()=>setSaved(false),1200)},450);return()=>clearTimeout(t)},[data,step,session,tenantId,pct]);
 async function emailLink(e){e.preventDefault();if(!data.email)return;setBusy(true);const {error}=await supabase.auth.signInWithOtp({email:data.email,options:{emailRedirectTo:window.location.origin+'/website-setup',shouldCreateUser:true,data:{business_name:data.businessName||'My business',service_type:'website',onboarding_answers:data}}});setMessage(error?error.message:'Check your email for your secure sign-in link. It will bring you back here.');setBusy(false)}
 async function upload(file){if(!file||!tenantId)return;setBusy(true);const ext=(file.name.split('.').pop()||'png').toLowerCase(),path=tenantId+'/website-logo-'+Date.now()+'.'+ext;const {error}=await supabase.storage.from('onboarding-assets').upload(path,file);if(error)setMessage(error.message);else{await supabase.from('onboarding').update({logo_path:path,service_type:'website'}).eq('tenant_id',tenantId);setLogoPath(path);setMessage('Logo uploaded securely.')}setBusy(false)}
 async function submit(){if(!session){setMessage('Use your secure email link first so we can attach this setup to your account.');return}setBusy(true);const {error}=await supabase.from('onboarding').update({service_type:'website',answers:data,current_step:4,progress:100,logo_path:logoPath||null,status:'submitted',submitted_at:new Date().toISOString()}).eq('tenant_id',tenantId);setMessage(error?'We could not submit your website setup. Please try again.':'Submitted. We have everything you provided and can now prepare your website.');setBusy(false)}
 return <main className="setupPage"><header className="setupHeader"><Link href="/"><img src="/DS Logo latest tagline.png" alt="Diamant Solutions"/></Link><span>{saved?'Saved':session?'Securely saved online':'Progress saves on this device'}</span></header><section className="setupWrap"><div className="setupIntro"><p>WEBSITE SETUP</p><h1>Let’s build the right website.</h1><span>{session?'Your answers are securely saved to your account.':'Answer what you can now. Use your secure email link to continue on any device.'}</span></div>{!session&&<form className="secureAccount" onSubmit={emailLink}><div><b>Save and continue securely</b><span>We’ll email you a secure sign-in link. No password needed.</span></div><input type="email" value={data.email||''} onChange={e=>update('email',e.target.value)} placeholder="Email address" required/><button disabled={busy}>{busy?'Sending...':'Email my secure link'}</button></form>}{message&&<div className="setupMessage">{message}</div>}<div className="progress"><div><b>Step {step+1} of {steps.length}</b><span>{pct}% complete</span></div><i><em style={{width:pct+'%'}}/></i></div><div className="setupCard"><small>{steps[step].title.toUpperCase()}</small><h2>{steps[step].title}</h2>{steps[step].fields.map(([key,label])=><label key={key}><b>{label}</b>{key==='logo'?(session?<div className="logoUpload"><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>upload(e.target.files?.[0])}/>{logoPath&&<span>Uploaded ✓</span>}</div>:<div className="uploadNote">Use your secure email link above before uploading your logo.</div>):longKeys.includes(key)?<textarea value={data[key]||''} onChange={e=>update(key,e.target.value)} placeholder="Type your answer here..."/>:<input value={data[key]||''} onChange={e=>update(key,e.target.value)} placeholder="Type here..."/>}</label>)}<div className="setupActions">{step>0?<button className="secondary" onClick={()=>setStep(x=>x-1)}>Back</button>:<Link className="secondary" href="/websites">Back to websites</Link>}<span>{session?'Saved securely as you go.':'Saved on this device as you go.'}</span>{step<4?<button onClick={()=>setStep(x=>x+1)}>Save & continue</button>:<button disabled={busy} onClick={submit}>{busy?'Saving...':'Submit my website setup'}</button>}</div></div><p className="setupHelp">{session?'You can return later from another device using the same email address.':'You can keep filling this in now, then use the secure link before submitting.'}</p></section></main>}