'use client';
import DiamantCredit from '../../../components/admin/DiamantCredit';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import '../../zmanim.css';
const defs={
 havdalah_locations:{name:'Locations',icon:'🌍',hint:'Set each city’s timezone and Havdalah calculation.',fields:['name','country_code','timezone','latitude','longitude','havdalah_degrees','enabled']},
 havdalah_lines:{name:'Phone lines',icon:'☎',hint:'Route each incoming number to a city.',fields:['number','location_id','enabled']},
 havdalah_hosts:{name:'Hosts',icon:'🎙',hint:'Add a host once, then assign them to sessions.',fields:['name','phone','enabled']},
 havdalah_slots:{name:'Sessions',icon:'🕒',hint:'Add as many sessions as needed. Offsets are minutes after local Havdalah.',fields:['location_id','label','offset_minutes','sort_order','enabled']},
 havdalah_assignments:{name:'Host assignments',icon:'👥',hint:'Priority 1 is primary; 2, 3 and higher are backups.',fields:['slot_id','host_id','priority']},
 havdalah_exceptions:{name:'Cancelled dates',icon:'📅',hint:'Disable a particular session for one date.',fields:['slot_id','session_date','disabled','notes']},
 havdalah_host_absences:{name:'Host absences',icon:'🚫',hint:'Exclude a host from sessions on a particular date.',fields:['host_id','session_date','reason']}
};
const labels={country_code:'Country code',timezone:'Time zone',latitude:'Latitude',longitude:'Longitude',havdalah_degrees:'Havdalah angle (degrees)',location_id:'Location',host_id:'Host',slot_id:'Session',offset_minutes:'Minutes after Havdalah',sort_order:'Display order',session_date:'Date',phone:'Phone number',number:'Phone number',priority:'Priority',enabled:'Active',disabled:'Cancel session',notes:'Notes'};
const supa=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY):null;
const colors={ink:'#152b45',muted:'#65758a',line:'#e3eaf2',blue:'#175cd3'};
const inputStyle={padding:'11px 12px',border:'1px solid #ccd7e5',borderRadius:9,width:'100%',background:'#fff',fontSize:14,color:colors.ink};
const btn=(primary=false)=>({border:'1px solid '+(primary?colors.blue:'#d6e0ed'),background:primary?colors.blue:'#fff',color:primary?'white':colors.ink,borderRadius:9,padding:'10px 15px',fontSize:14,fontWeight:600,letterSpacing:'0.25px',cursor:'pointer'});
export default function HavdalahAdmin(){
 const [recovery,setRecovery]=useState(false),[newPassword,setNewPassword]=useState(''),[notice,setNotice]=useState(''),[session,setSession]=useState(null),[data,setData]=useState({}),[tab,setTab]=useState('havdalah_slots'),[editing,setEditing]=useState(null),[form,setForm]=useState({}),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 useEffect(()=>{if(!supa)return;supa.auth.getSession().then(x=>setSession(x.data.session));const {data:s}=supa.auth.onAuthStateChange((event,v)=>{setSession(v);if(event==='PASSWORD_RECOVERY'||window.location.hash.includes('type=recovery')||window.location.search.includes('type=recovery'))setRecovery(true)});return()=>s.subscription.unsubscribe();},[]);
 async function load(){if(!session)return;setBusy(true);try{const r=await fetch('/api/havdalah/admin',{headers:{Authorization:'Bearer '+session.access_token}});const j=await r.json();if(!r.ok){if(r.status===401){setError(j.error||'Session expired. Sign out and sign in again.');return;}throw Error(j.error)}setData(j);setError('');}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(session&&!recovery)load();},[session,recovery]);
 const friendly=(table,id)=>{const x=(data[table]||[]).find(v=>v.id===id);return x?.name||x?.label||x?.number||'Unknown';};
 const display=(f,v)=>{if(v===null||v===undefined||v==='')return 'Not set';if(typeof v==='boolean')return v?'Yes':'No';if(f==='location_id')return friendly('havdalah_locations',v);if(f==='host_id')return friendly('havdalah_hosts',v);if(f==='slot_id')return friendly('havdalah_slots',v);if(f==='offset_minutes')return v+' minutes';return String(v)};
 const open=(row)=>{setError('');setForm(row?Object.fromEntries(defs[tab].fields.map(f=>[f,row[f]??''])):{enabled:true,disabled:true,priority:1,sort_order:1,havdalah_degrees:8.5});setEditing(row?.id||'new')};
 async function save(action,id){
  setBusy(true);try{const r=await fetch('/api/havdalah/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({table:tab,action,id,values:action==='delete'?{}:form})});const j=await r.json();if(!r.ok)throw Error(j.error);setEditing(null);setForm({});await load()}catch(e){setError(e.message)}finally{setBusy(false)}
 }
 const field=(f)=>{const v=form[f]??'';const update=x=>setForm(y=>({...y,[f]:x}));if(f==='enabled'||f==='disabled')return <select style={inputStyle} value={String(v)} onChange={e=>update(e.target.value==='true')}><option value="true">Yes</option><option value="false">No</option></select>;
 if(f.endsWith('_id')){const t=f==='location_id'?'havdalah_locations':f==='host_id'?'havdalah_hosts':'havdalah_slots';return <select required style={inputStyle} value={v} onChange={e=>update(e.target.value)}><option value="">Choose {labels[f].toLowerCase()}</option>{(data[t]||[]).map(x=><option key={x.id} value={x.id}>{x.name||x.label||x.number}{x.country_code?' ('+x.country_code+')':''}</option>)}</select>}
 return <input style={inputStyle} type={f==='session_date'?'date':/latitude|longitude|degrees|minutes|priority|sort_order/.test(f)?'number':'text'} step={/latitude|longitude|degrees/.test(f)?'any':'1'} placeholder={f==='timezone'?'Europe/London':f==='country_code'?'GB':f==='phone'||f==='number'?'+44…':labels[f]||f} value={v} onChange={e=>update(e.target.value)} required={!['notes','reason'].includes(f)}/>};
 const rows=(data[tab]||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
 return <main style={{background:'#f5f8fc',minHeight:'100vh',color:colors.ink,fontFamily:'Arial, sans-serif',display:'flex',flexDirection:'column'}}><header style={{background:'#fff',borderBottom:'1px solid '+colors.line,padding:'18px 24px',boxShadow:'0 2px 14px rgba(19,43,75,.035)'}}><div style={{maxWidth:1160,margin:'0 auto',display:'flex',alignItems:'center',justifyContent:'space-between',gap:22,flexWrap:'wrap'}}><a href="/" aria-label="Diamant Solutions home" style={{display:'flex',alignItems:'center',minHeight:45}}><img src="/DS Logo latest tagline.png" alt="Diamant Solutions" style={{width:170,maxWidth:'min(70vw,170px)',height:'auto',display:'block',objectFit:'contain'}}/></a><div style={{display:'flex',alignItems:'center',gap:16,flexWrap:'wrap'}}><span style={{fontSize:12,letterSpacing:'1px',fontWeight:700,color:colors.muted,textTransform:'uppercase'}}>Hotline management</span><a href="/havdalah" style={{fontSize:14,color:colors.blue,textDecoration:'none',fontWeight:700,border:'1px solid '+colors.line,borderRadius:9,padding:'11px 15px'}}>Public hotline ↗</a></div></div></header><div style={{maxWidth:1160,width:'100%',margin:'0 auto',padding:'30px 18px',flex:1,boxSizing:'border-box'}}>
 <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap',marginBottom:24}}><div><h1 style={{margin:'7px 0',fontSize:30,letterSpacing:'0.4px'}}>Havdalah Hotline</h1><div style={{color:colors.muted}}>Operations and scheduling</div></div>{session&&<div style={{display:'flex',gap:8}}><button style={btn()} onClick={load}>↻ Refresh</button><button style={btn()} onClick={async()=>{await supa.auth.signOut();setSession(null);setRecovery(false);setError('');setNotice('');setData({})}}>Sign out</button></div>}</div>
 {recovery&&session?<div style={{background:'#fff',border:'1px solid '+colors.line,borderRadius:14,padding:25,maxWidth:450}}><h2>Set your password</h2><form style={{display:'grid',gap:12}} onSubmit={async e=>{e.preventDefault();setError('');const {error:e2}=await supa.auth.updateUser({password:newPassword});if(e2)setError(e2.message);else{setRecovery(false);setNewPassword('');setNotice('Password saved. You are signed in.');if(typeof window!=='undefined')window.history.replaceState(null,'',window.location.pathname)}}}><input style={inputStyle} type="password" minLength={8} placeholder="New password (at least 8 characters)" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/><button style={btn(true)}>Save password</button></form>{error&&<p role="alert" style={{color:'#9b2222'}}>{error}</p>}</div>:!session?<div style={{background:'#fff',border:'1px solid '+colors.line,borderRadius:14,padding:25,maxWidth:450}}><h2>Admin sign in</h2><form onSubmit={async e=>{e.preventDefault();const {error}=await supa.auth.signInWithPassword({email,password});if(error)setError(error.message)}} style={{display:'grid',gap:12}}><input style={inputStyle} type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required/><input style={inputStyle} type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button style={btn(true)}>Sign in</button></form><button type="button" style={{...btn(),marginTop:12}} onClick={async()=>{setError('');setNotice('');const address=email.trim()||'mark@diamantsolutions.co.uk';const {error:e2}=await supa.auth.resetPasswordForEmail(address,{redirectTo:'https://diamantsolutions.co.uk/admin/havdalah'});if(e2)setError(e2.message);else setNotice('Password setup email requested. Check your inbox and spam folder.')}}>Set or reset password</button>{error&&<p role="alert" style={{color:'#9b2222',fontSize:14}}>{error}</p>}{notice&&<p role="status" style={{color:'#176b43',fontSize:14}}>{notice}</p>}</div>:<>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(165px,1fr))',gap:12,marginBottom:22}}>{[['Locations',(data.havdalah_locations||[]).length],['Active sessions',(data.havdalah_slots||[]).filter(x=>x.enabled).length],['Hosts',(data.havdalah_hosts||[]).length],['Phone lines',(data.havdalah_lines||[]).length]].map(([k,v])=><div key={k} style={{background:'#fff',border:'1px solid '+colors.line,borderRadius:12,padding:18}}><div style={{color:colors.muted,fontSize:13}}>{k}</div><div style={{fontSize:27,fontWeight:700,marginTop:6}}>{v}</div></div>)}</div>
 <div style={{display:'flex',gap:8,overflowX:'auto',paddingBottom:10,marginBottom:15}}>{Object.entries(defs).map(([k,v])=><button key={k} onClick={()=>{setTab(k);setEditing(null);setSearch('');setError('')}} style={{...btn(tab===k),whiteSpace:'nowrap'}}>{v.icon} {v.name}</button>)}</div>
 <section style={{background:'#fff',border:'1px solid '+colors.line,borderRadius:14,overflow:'hidden'}}><div style={{padding:22,borderBottom:'1px solid '+colors.line,display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h2 style={{margin:'0 0 6px',fontSize:21,letterSpacing:'0.35px'}}>{defs[tab].name}</h2><p style={{margin:0,color:colors.muted,fontSize:14}}>{defs[tab].hint}</p></div><button style={btn(true)} onClick={()=>open(null)}>+ Add {tab==='havdalah_hosts'?'host':tab==='havdalah_slots'?'session':'new'}</button></div>
 <div style={{padding:'14px 22px'}}><input style={{...inputStyle,maxWidth:320}} placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr style={{background:'#f7f9fc'}}>{defs[tab].fields.map(f=><th key={f} style={{textAlign:'left',padding:'12px 15px',whiteSpace:'nowrap',color:colors.muted}}>{labels[f]||f.replaceAll('_',' ')}</th>)}<th style={{padding:12}}>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{defs[tab].fields.map(f=><td key={f} style={{borderTop:'1px solid '+colors.line,padding:'12px 15px',whiteSpace:'nowrap'}}>{display(f,row[f])}</td>)}<td style={{borderTop:'1px solid '+colors.line,padding:10,whiteSpace:'nowrap'}}><button style={btn()} onClick={()=>open(row)}>Edit</button> <button style={{...btn(),color:'#bd3030'}} onClick={()=>{if(window.confirm('Delete this record? This cannot be undone.'))save('delete',row.id)}}>Delete</button></td></tr>)}</tbody></table>{rows.length===0&&<p style={{padding:28,textAlign:'center',color:colors.muted}}>No records yet. Add your first one above.</p>}</div></section>
 {editing&&<div style={{position:'fixed',inset:0,background:'rgba(15,31,49,.5)',zIndex:20,display:'flex',justifyContent:'flex-end'}} onClick={()=>setEditing(null)}><div onClick={e=>e.stopPropagation()} style={{width:'min(100%,480px)',background:'#fff',height:'100%',overflowY:'auto',padding:26,boxShadow:'-8px 0 35px #0002'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>{editing==='new'?'Add':'Edit'} {defs[tab].name.toLowerCase()}</h2><button style={btn()} onClick={()=>setEditing(null)}>✕</button></div><p style={{color:colors.muted}}>{defs[tab].hint}</p><form onSubmit={e=>{e.preventDefault();save(editing==='new'?'create':'update',editing)}} style={{display:'grid',gap:18,marginTop:24}}>{defs[tab].fields.map(f=><label key={f} style={{display:'grid',gap:7,fontSize:13,fontWeight:600,letterSpacing:'0.25px'}}>{labels[f]||f.replaceAll('_',' ')}{field(f)}</label>)}<button disabled={busy} style={btn(true)}>{busy?'Saving…':'Save changes'}</button></form></div></div>}
 </>}{session&&!recovery&&error&&<div role="alert" style={{position:'fixed',top:20,left:'50%',transform:'translateX(-50%)',zIndex:1000,background:'#fff0f0',border:'2px solid #c0392b',boxShadow:'0 8px 30px #0003',borderRadius:12,padding:20,color:'#9b2222',maxWidth:480,width:'calc(100% - 40px)',boxSizing:'border-box'}}><strong>Admin error</strong><p>{error}</p><button style={btn()} onClick={load}>Retry</button> <button style={btn()} onClick={async()=>{await supa.auth.signOut();setSession(null);setError('')}}>Sign out and log in</button></div>}{session&&!recovery&&notice&&<p role="status">{notice}</p>}</div><footer className="zfooter toolFooter noprint"><div className="toolFooterLinks"><strong>Havdalah Hotline</strong><a href="/havdalah">Hotline information</a><a href="/tools">Free Tools</a></div><DiamantCredit dark/><div className="toolFooterLinks toolFooterRight"><strong>Diamant Solutions</strong><a href="/">Main website</a><a href="mailto:info@diamantsolutions.co.uk">info@diamantsolutions.co.uk</a><a href="tel:+442032845074">0203 284 5074</a></div></footer></main>
}
