import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {runtimeTenant} from "@/lib/business-software/runtime";
import {centralRest,centralStorage} from "@/lib/business-software/db";
const SB="https://iepqggrfenfqrqyzqyed.supabase.co",KEY="sb_publishable_ivTCLFGFroexc-3IHe25bg_qhzg_GIy";
async function ctx(){const tenant=await runtimeTenant();if(!tenant?.id)return null;const token=(await cookies()).get("bms_access_token")?.value;if(!token)return null;const u=await fetch(SB+"/auth/v1/user",{headers:{apikey:KEY,Authorization:"Bearer "+token},cache:"no-store"});if(!u.ok)return null;const auth=await u.json(),r=await centralRest("business_software_users?tenant_id=eq."+tenant.id+"&auth_user_id=eq."+auth.id+"&status=eq.active&select=id,email,display_name&limit=1"),user=(await r.json().catch(()=>[]))[0];return user?{tenant,user}:null}
async function taskOk(tenant:string,id:string){const r=await centralRest("business_software_tasks?tenant_id=eq."+encodeURIComponent(tenant)+"&id=eq."+encodeURIComponent(id)+"&select=id&limit=1");return !!(await r.json().catch(()=>[]))[0]}
export async function POST(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorised"},{status:401});const fd=await req.formData(),taskId=String(fd.get("task_id")||""),file=fd.get("file");if(!taskId||!await taskOk(c.tenant.id,taskId))return NextResponse.json({error:"Task not found"},{status:404});if(!(file instanceof File))return NextResponse.json({error:"Choose a file"},{status:400});if(file.size>10000000)return NextResponse.json({error:"File must be under 10MB"},{status:400});const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-"),path=c.tenant.id+"/"+taskId+"/"+Date.now()+"-"+safe,up=await centralStorage("object/bms-task-files/"+path,{method:"POST",headers:{"Content-Type":file.type||"application/octet-stream","x-upsert":"false"},body:await file.arrayBuffer()});if(!up.ok)return NextResponse.json({error:"Unable to upload file"},{status:500});const ins=await centralRest("business_software_task_attachments",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({tenant_id:c.tenant.id,task_id:taskId,storage_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size,uploaded_by_user_id:c.user.id})}),rows=await ins.json().catch(()=>[]);if(!ins.ok){await centralStorage("object/bms-task-files/"+path,{method:"DELETE"});return NextResponse.json({error:"Unable to save attachment"},{status:500})}await centralRest("business_software_task_events",{method:"POST",body:JSON.stringify({tenant_id:c.tenant.id,task_id:taskId,actor_user_id:c.user.id,event_type:"attachment_added",detail:{file_name:file.name}})});return NextResponse.json({attachment:rows[0]},{status:201})}
export async function GET(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorised"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Attachment required"},{status:400});const r=await centralRest("business_software_task_attachments?tenant_id=eq."+c.tenant.id+"&id=eq."+encodeURIComponent(id)+"&select=*&limit=1"),a=(await r.json().catch(()=>[]))[0];if(!a)return NextResponse.json({error:"Attachment not found"},{status:404});const obj=await centralStorage("object/authenticated/bms-task-files/"+a.storage_path,{cache:"no-store"});if(!obj.ok)return NextResponse.json({error:"File unavailable"},{status:404});return new NextResponse(await obj.arrayBuffer(),{headers:{"Content-Type":a.mime_type||"application/octet-stream","Content-Disposition":'inline; filename="'+String(a.file_name).replaceAll('"',"")+'"',"Cache-Control":"private, max-age=60"}})}
export async function DELETE(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorised"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Attachment required"},{status:400});const r=await centralRest("business_software_task_attachments?tenant_id=eq."+c.tenant.id+"&id=eq."+encodeURIComponent(id)+"&select=*&limit=1"),a=(await r.json().catch(()=>[]))[0];if(!a)return NextResponse.json({error:"Attachment not found"},{status:404});await centralStorage("object/bms-task-files/"+a.storage_path,{method:"DELETE"});await centralRest("business_software_task_attachments?tenant_id=eq."+c.tenant.id+"&id=eq."+encodeURIComponent(id),{method:"DELETE"});await centralRest("business_software_task_events",{method:"POST",body:JSON.stringify({tenant_id:c.tenant.id,task_id:a.task_id,actor_user_id:c.user.id,event_type:"attachment_deleted",detail:{file_name:a.file_name}})});return NextResponse.json({ok:true})}