'use client';
import {useEffect,useState} from 'react';import DiamantCredit from '../../components/admin/DiamantCredit';import '../zmanim.css';import {sunset,formatTime,localDateLabel} from '../../lib/zmanim';
export default function Shkiah(){const[loc,setLoc]=useState(null),[place,setPlace]=useState(''),[err,setErr]=useState(''),[shift,setShift]=useState(0),[search,setSearch]=useState(false),[q,setQ]=useState(''),[results,setResults]=useState([]);const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
async function nameLoc(v){try{const j=await fetch(`/api/zmanim/location?lat=${v.lat}&lon=${v.lon}`).then(r=>r.json());setPlace(j.name||'')}catch{}}
function current(){setErr('');navigator.geolocation.getCurrentPosition(p=>{const v={lat:p.coords.latitude,lon:p.coords.longitude};setLoc(v);nameLoc(v);setSearch(false)},()=>setErr('Please allow location access to calculate Shkiah for your area.'),{enableHighAccuracy:true,timeout:10000})}
async function find(e){e.preventDefault();const j=await fetch('/api/zmanim/search?q='+encodeURIComponent(q)).then(r=>r.json());setResults(j.results||[])}
function choose(x){setLoc({lat:x.lat,lon:x.lon});setPlace(x.name);setSearch(false);setResults([])}
useEffect(()=>current(),[]);
const d=new Date();d.setDate(d.getDate()+shift);const heb=new Intl.DateTimeFormat('en-u-ca-hebrew',{day:'numeric',month:'long',year:'numeric'}).format(d),s=loc?sunset(new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate(),12)),loc.lat,loc.lon):null;
return <><div className="zpowered"><DiamantCredit compact/></div><main className="zpage"><section className="zcard"><h1 className="ztitle">Shkiah</h1><div className="zdate">{localDateLabel(d,tz)}</div><div className="zhebrew">{heb}</div>{loc?<><div className="zlabel">Shkiah</div><div className="ztime">{formatTime(s,tz)}</div><div className="zlocation">📍 <span className="zplace">{place||`${loc.lat.toFixed(3)}, ${loc.lon.toFixed(3)}`}</span></div><div className="zlocactions"><button className="ztextbtn" onClick={()=>setSearch(!search)}>Change location</button>{search&&<button className="ztextbtn" onClick={current}>Back to my location</button>}</div></>:<button className="zbtn" onClick={current}>Use my location</button>}{search&&<div className="zsearch"><form onSubmit={find}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, area or postcode"/><button className="zbtn">Search</button></form>{results.map((x,i)=><button className="zresult" key={i} onClick={()=>choose(x)}>{x.name}</button>)}</div>}{err&&<p className="zerror">{err}</p>}<div className="znav"><button className="zbtn secondary" onClick={()=>setShift(x=>x-1)}>Previous</button><button className="zbtn secondary" onClick={()=>setShift(0)}>Today</button><button className="zbtn secondary" onClick={()=>setShift(x=>x+1)}>Next</button></div><p className="znote">For time-sensitive mitzvos, do not rely on the final moment. Local horizon, elevation and atmospheric conditions can affect observed sunset. For halachic questions, consult your Rav.</p><div className="zlinks"><a className="zmethod" href="/zmanim-methodology">How are these times calculated?</a><br/><a href="/shabbos">Shabbos & Yom Tov times</a></div></section></main><footer className="zfooter"><DiamantCredit dark/></footer></>}