'use client';
import {useEffect,useState} from 'react'; import DiamantCredit from '../../components/admin/DiamantCredit'; import '../zmanim.css'; import {sunset,formatTime,localDateLabel} from '../../lib/zmanim';
const KEY='ds-zmanim-location';
export default function Shkiah(){
 const [loc,setLoc]=useState(null),[place,setPlace]=useState(''),[err,setErr]=useState(''),[shift,setShift]=useState(0);
 const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
 async function nameLoc(v){try{const r=await fetch(`/api/zmanim/location?lat=${v.lat}&lon=${v.lon}`),j=await r.json();setPlace(j.name||'')}catch{}} function ask(){setErr('');navigator.geolocation.getCurrentPosition(p=>{const v={lat:p.coords.latitude,lon:p.coords.longitude};localStorage.setItem(KEY,JSON.stringify(v));setLoc(v);nameLoc(v)},()=>setErr('Location is needed to calculate Shkiah for your area. Please allow location access and try again.'),{enableHighAccuracy:true,timeout:10000})}
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.lat){setLoc(v);nameLoc(v)}else ask()}catch{ask()}},[]);
 const d=new Date(); d.setDate(d.getDate()+shift); const heb=new Intl.DateTimeFormat('en-u-ca-hebrew',{day:'numeric',month:'long',year:'numeric'}).format(d); const s=loc?sunset(new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate(),12)),loc.lat,loc.lon):null;
 return <><div className="zpowered"><DiamantCredit compact/></div><main className="zpage"><section className="zcard"><h1 className="ztitle">Shkiah</h1><div className="zdate">{localDateLabel(d,tz)}</div><div className="zhebrew">{heb}</div>{loc?<><div className="zlabel">Shkiah</div><div className="ztime">{formatTime(s,tz)}</div><div className="zlocation">📍 <span className="zplace">{place||`${loc.lat.toFixed(3)}, ${loc.lon.toFixed(3)}`}</span> <button className="zbtn secondary" onClick={ask}>Update</button></div></>:<button className="zbtn" onClick={ask}>Use my location</button>}{err&&<p className="zerror">{err}</p>}<div className="znav"><button className="zbtn secondary" onClick={()=>setShift(x=>x-1)}>← Previous</button><button className="zbtn secondary" onClick={()=>setShift(0)}>Today</button><button className="zbtn secondary" onClick={()=>setShift(x=>x+1)}>Next →</button></div><p className="znote">For time-sensitive mitzvos, do not rely on the final moment. Local horizon, elevation and atmospheric conditions can affect observed sunset. For halachic questions, consult your Rav.</p><div className="zlinks"><a href="/shabbos">Shabbos & Yom Tov times →</a></div></section></main><footer className="zfooter"><DiamantCredit dark/></footer></>
}