"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase-browser";
const TENANT="3ebc2265-8842-4826-b464-71783d6cf841";
const resources=["jobs","customers","payments","costs","quotes","invoices","files","people","assignments","audit"];
const fields=["status","manager","next_action","internal_notes","job_type","customer_requirements","next_action_at","scheduled_at","expected_completion_at"] as const;
const money=(v:any)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number(v||0));
export default function MjOperationalJob({reference}:{reference:string}){
 const [token,setToken]=useState(""),[data,setData]=useState<Record<string,any[]>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[finance,setFinance]=useState<"payments"|"costs"|null>(null),[financeForm,setFinanceForm]=useState<Record<string,string>>({});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setToken(data.session?.access_token||""));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setToken(s?.access_token||""));return()=>subscription.unsubscribe()},[]);
 async function get(resource:string,access:string){const response=await fetch("/api/business-software/tenant-data?"+new URLSearchParams({tenant_id:TENANT,resource}),{headers:{Authorization:"Bearer "+access},cache:"no-store"});const body=await response.json();if(!response.ok)throw Error(body.error||"Cannot load "+resource);return body.data as any[]}
 useEffect(()=>{if(!token)return;let active=true;Promise.all(resources.map(async resource=>[resource,await get(resource,token)] as const)).then(all=>{if(active)setData(Object.fromEntries(all))}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[token]);
 const job=data.jobs?.find(j=>j.reference===reference),customer=data.customers?.find(c=>c.id===job?.customer_id);
 async function saveJob(e:React.FormEvent){e.preventDefault();if(!job)return;setBusy(true);setError("");try{const values=Object.fromEntries(fields.filter(k=>form[k]!==String(job[k]??"")).map(k=>[k,form[k]||null]));if(!Object.keys(values).length){setEditing(false);return}const r=await fetch("/api/business-software/tenant-update",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({tenant_id:TENANT,resource:"jobs",id:job.id,values})});const body=await r.json();if(!r.ok)throw Error(body.error);setData(prev=>({...prev,jobs:prev.jobs.map(j=>j.id===job.id?{...j,...values}:j)}));setEditing(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function saveFinance(e:React.FormEvent){e.preventDefault();if(!job||!finance)return;setBusy(true);setError("");try{const values:any={...financeForm,job_id:job.id};for(const k of ["amount","actual_amount","estimated_amount","paid_amount"])if(values[k]!==undefined&&values[k]!=="")values[k]=Number(values[k]);else delete values[k];const r=await fetch("/api/business-software/staging-finance",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({tenant_id:TENANT,resource:finance,values})});const b=await r.json();if(!r.ok)throw Error(b.error);setData(prev=>({...prev,[finance!]:[b.record,...(prev[finance!]||[])]}));setFinance(null);setFinanceForm({})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function download(path:string){try{const r=await fetch("/api/business-software/private-file",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({tenant_id:TENANT,path})});const body=await r.json();if(!r.ok)throw Error(body.error);location.assign(body.url)}catch(e:any){setError(e.message)}}
 const payments=(data.payments||[]).filter(p=>p.job_id===job?.id),costs=(data.costs||[]).filter(c=>c.job_id===job?.id);
 const received=payments.filter(p=>p.direction==="customer_in"&&(p.paid_at||p.payment_type==="historical_xero_paid")).reduce((s,p)=>s+Number(p.amount||0),0),contractorPaid=payments.filter(p=>p.direction==="subcontractor_out").reduce((s,p)=>s+Number(p.amount||0),0),actualCosts=costs.reduce((s,c)=>s+Number(c.actual_amount||0),0);
 return <main className="mx-auto max-w-6xl p-4 text-[#141414] sm:p-6"><Link href="/bms-runtime/jobs" className="text-sm underline">← Jobs</Link><h1 className="mt-4 text-3xl font-black">{reference}</h1><p className="mb-5 text-sm text-black/50">M&J · Shared BMS · Isolated staging</p>{error&&<p role="alert" className="my-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{!token&&<Link href="/bms-mj-preview" className="underline">Sign in to staging</Link>}
 {job?<><section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">{[customer?.first_name,customer?.last_name].filter(Boolean).join(" ")}</h2><p>{job.job_type} · {job.status}</p><p>Manager: {job.manager||"Unassigned"} · Next: {job.next_action||"—"}</p><p>Quoted: {money(job.quoted_amount)}</p></div><button onClick={()=>{setForm(Object.fromEntries(fields.map(k=>[k,String(job[k]??"")])));setEditing(v=>!v)}} className="h-11 rounded-xl bg-[#e66a24] px-4 font-bold text-white">{editing?"Cancel":"Edit job"}</button></div>
 {editing&&<form onSubmit={saveJob} className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-2">{fields.map(k=><label key={k} className="text-sm font-bold capitalize">{k.replaceAll("_"," ")}{["internal_notes","customer_requirements"].includes(k)?<textarea className="mt-1 block w-full rounded-lg border p-3" value={form[k]||""} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/>:<input className="mt-1 block w-full rounded-lg border p-3" value={form[k]||""} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/>}</label>)}<button disabled={busy} className="rounded-xl bg-[#e66a24] px-4 py-3 font-bold text-white disabled:opacity-50">Save job changes</button></form>}</section>
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Customer receipts",received],["Contractor paid",contractorPaid],["Recorded actual costs",actualCosts],["Quoted balance",Math.max(0,Number(job.quoted_amount||0)-received-Number(job.written_off_amount||0))]].map(([label,value])=><div key={String(label)} className="rounded-xl border bg-white p-4"><p className="text-sm text-black/60">{label}</p><p className="mt-2 text-xl font-black">{money(value)}</p></div>)}</div><p className="mt-2 text-xs text-black/50">Receipts and costs are separate measures; the difference is not net profit.</p>
 <div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>{setFinance("payments");setFinanceForm({direction:"customer_in",payment_type:"manual",amount:"",paid_at:new Date().toISOString()})}} className="rounded-xl bg-[#e66a24] px-4 py-2 font-bold text-white">+ Payment</button><button onClick={()=>{setFinance("costs");setFinanceForm({category:"Materials",actual_amount:""})}} className="rounded-xl border bg-white px-4 py-2 font-bold">+ Job cost</button></div>
 {finance&&<form onSubmit={saveFinance} className="mt-4 grid gap-3 rounded-xl border bg-white p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 text-xl font-black">Add {finance==="payments"?"payment":"job cost"}</h2>{(finance==="payments"?["direction","payment_type","amount","payment_method","counterparty","paid_at","notes"]:["category","supplier","estimated_amount","actual_amount","paid_amount","notes"]).map(k=><label key={k} className="text-sm font-bold capitalize">{k.replaceAll("_"," ")}{k==="direction"?<select className="mt-1 block w-full rounded-lg border p-3" value={financeForm[k]||""} onChange={e=>setFinanceForm(p=>({...p,[k]:e.target.value}))}><option value="customer_in">Customer receipt</option><option value="subcontractor_out">Contractor payment</option></select>:<input required={["payment_type","amount","category"].includes(k)} type={["amount","estimated_amount","actual_amount","paid_amount"].includes(k)?"number":"text"} min={["amount","estimated_amount","actual_amount","paid_amount"].includes(k)?"0":undefined} step="any" className="mt-1 block w-full rounded-lg border p-3" value={financeForm[k]||""} onChange={e=>setFinanceForm(p=>({...p,[k]:e.target.value}))}/>}</label>)}<div className="flex gap-2"><button disabled={busy} className="rounded-xl bg-[#e66a24] px-4 py-2 font-bold text-white">Save</button><button type="button" onClick={()=>setFinance(null)} className="rounded-xl border px-4 py-2">Cancel</button></div></form>}
 {resources.filter(x=>!["jobs","customers"].includes(x)).map(resource=>{const rows=(data[resource]||[]).filter(row=>row.job_id===job.id||(resource==="audit"&&row.entity_id===job.id));return <section key={resource} className="mt-5 rounded-2xl border bg-white p-5"><h2 className="text-lg font-black capitalize">{resource} ({rows.length})</h2>{rows.map(row=><div key={row.id} className="mt-2 border-t py-3 text-sm">{Object.entries(row).filter(([k])=>!["tenant_id"].includes(k)).map(([k,v])=><p key={k}><b>{k.replaceAll("_"," ")}:</b> {v==null?"—":typeof v==="object"?JSON.stringify(v):String(v)}</p>)}{resource==="files"&&row.storage_path&&<button onClick={()=>download(row.storage_path)} className="font-bold text-[#e66a24] underline">Download private file</button>}</div>)}</section>})}</>:token?<p>Loading job…</p>:null}</main>;
}