"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {supabase} from "@/lib/supabase-browser";
const TENANT="3ebc2265-8842-4826-b464-71783d6cf841";
export default function MjOperationalNewJob(){
 const router=useRouter(),[token,setToken]=useState(""),[customers,setCustomers]=useState<any[]>([]),[customer,setCustomer]=useState(""),[jobType,setJobType]=useState(""),[manager,setManager]=useState(""),[notes,setNotes]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setToken(data.session?.access_token||""));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setToken(s?.access_token||""));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!token)return;fetch("/api/business-software/tenant-data?"+new URLSearchParams({tenant_id:TENANT,resource:"customers"}),{headers:{Authorization:"Bearer "+token}}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);setCustomers(b.data)}).catch(e=>setError(e.message))},[token]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/business-software/staging-job",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({customer_id:customer,job_type:jobType,manager,notes})});const b=await r.json();if(!r.ok)throw Error(b.error);router.push("/bms-runtime/jobs/"+b.job.reference)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="mx-auto max-w-2xl p-6"><Link className="underline" href="/bms-runtime/jobs">← Jobs</Link><h1 className="my-5 text-3xl font-black">New M&J job</h1><p className="mb-5 text-sm">Shared BMS · Isolated staging only</p>{error&&<p role="alert" className="mb-4 bg-red-50 p-3 text-red-700">{error}</p>}{!token?<Link href="/bms-mj-preview" className="underline">Sign in to staging</Link>:<form onSubmit={save} className="grid gap-4 rounded-xl border bg-white p-5"><label>Customer<select className="mt-1 block w-full rounded-lg border p-3" value={customer} onChange={e=>setCustomer(e.target.value)} required><option value="">Choose customer</option>{customers.map(c=><option key={c.id} value={c.id}>{[c.first_name,c.last_name].filter(Boolean).join(" ")}</option>)}</select></label><label>Job type<input className="mt-1 block w-full rounded-lg border p-3" value={jobType} onChange={e=>setJobType(e.target.value)} required/></label><label>Manager<input className="mt-1 block w-full rounded-lg border p-3" value={manager} onChange={e=>setManager(e.target.value)}/></label><label>Notes<textarea className="mt-1 block w-full rounded-lg border p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={busy} className="rounded-xl bg-[#17385f] p-3 font-bold text-white">{busy?"Creating…":"Create staging job"}</button></form>}</main>;
}
