"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase-browser";
const TENANT="3ebc2265-8842-4826-b464-71783d6cf841";
type Row=Record<string,any>;
type View="jobs"|"customers"|"quotes"|"invoices"|"payments"|"files"|"team";
const resources:Record<View,string>={jobs:"jobs",customers:"customers",quotes:"quotes",invoices:"invoices",payments:"payments",files:"files",team:"people"};
const money=(v:any)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number(v||0));
export default function MjOperationalDirectory({view}:{view:View}){
 const [token,setToken]=useState(""),[rows,setRows]=useState<Row[]>([]),[jobs,setJobs]=useState<Row[]>([]),[customers,setCustomers]=useState<Row[]>([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setToken(data.session?.access_token||""));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setToken(session?.access_token||""));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!token){setLoading(false);setError("Sign in to M&J staging first.");return}let active=true;setLoading(true);setError("");
 const get=async(resource:string)=>{const response=await fetch("/api/business-software/tenant-data?"+new URLSearchParams({tenant_id:TENANT,resource}),{headers:{Authorization:"Bearer "+token},cache:"no-store"});const body=await response.json();if(!response.ok)throw Error(body.error||"Unable to load "+resource);return body.data as Row[]};
 Promise.all([get(resources[view]),get("jobs"),get("customers")]).then(([data,j,c])=>{if(active){setRows(data);setJobs(j);setCustomers(c)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});
 return()=>{active=false}},[token,view]);
 const names=useMemo(()=>new Map(customers.map(c=>[c.id,[c.first_name,c.last_name].filter(Boolean).join(" ")])),[customers]);
 const jobRefs=useMemo(()=>new Map(jobs.map(j=>[j.id,j.reference])),[jobs]);
 const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())||String(names.get(r.customer_id)||"").toLowerCase().includes(search.toLowerCase()));
 async function edit(row:Row){const fields=view==="jobs"?["status","manager","next_action","internal_notes","job_type","customer_requirements"]:view==="customers"?["first_name","last_name","phone","email","address_line_1","city","postcode"]:[];if(!fields.length)return;const field=prompt("Field: "+fields.join(", "));if(!field||!fields.includes(field))return;const value=prompt("New "+field,String(row[field]??""));if(value===null)return;try{const res=await fetch("/api/business-software/tenant-update",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({tenant_id:TENANT,resource:view,id:row.id,values:{[field]:value}})});const b=await res.json();if(!res.ok)throw Error(b.error);setRows(current=>current.map(x=>x.id===row.id?{...x,[field]:value}:x))}catch(e:any){setError(e.message)}}
 const columns:Record<View,string[]>={jobs:["reference","customer_id","job_type","status","manager","quoted_amount","next_action"],customers:["first_name","last_name","phone","email","postcode"],quotes:["job_id","status","amount","sent_at"],invoices:["job_id","invoice_number","status","total","amount_due"],payments:["job_id","payment_type","direction","amount","paid_at"],files:["job_id","file_name","category"],team:["name","company","phone","relationship_type"]};
 return <main className="min-h-screen bg-[#f5f5f2] px-4 py-7 text-[#141414] sm:px-5 lg:px-8"><div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-black capitalize">{view}</h1><p className="text-sm text-black/50">M&J · Shared business management system · Isolated staging</p></div><Link className="rounded-xl border bg-white px-4 py-2" href="/bms-mj-preview">Staging account</Link></header>
 <nav className="my-5 flex flex-wrap gap-2">{(Object.keys(resources) as View[]).map(v=><Link key={v} className={"rounded-xl px-3 py-2 text-sm font-bold "+(v===view?"bg-[#17385f] text-white":"bg-white")} href={"/bms-runtime/"+(v==="team"?"team":v)}>{v}</Link>)}</nav>
 <input aria-label="Search" placeholder={"Search "+view} value={search} onChange={e=>setSearch(e.target.value)} className="w-full rounded-xl border bg-white p-3"/>
 {error&&<p role="alert" className="my-4 rounded-xl bg-red-50 p-3 text-red-700">{error} {!token&&<Link className="underline" href="/bms-mj-preview">Sign in</Link>}</p>}
 {loading?<p className="p-6">Loading…</p>:<div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{columns[view].map(c=><th className="border-b p-3" key={c}>{c.replaceAll("_"," ")}</th>)}{["jobs","customers"].includes(view)&&<th className="border-b p-3">Actions</th>}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-b">{columns[view].map(c=><td className="p-3" key={c}>{c==="customer_id"?names.get(r[c])||r[c]:c==="job_id"?jobRefs.get(r[c])||r[c]:c==="reference"?<Link className="font-bold text-[#e66a24]" href={"/bms-runtime/jobs/"+encodeURIComponent(r.reference)}>{r.reference}</Link>:["amount","total","amount_due","quoted_amount"].includes(c)?money(r[c]):r[c]==null?"—":String(r[c])}</td>)}{["jobs","customers"].includes(view)&&<td className="p-3"><button onClick={()=>edit(r)} className="rounded-lg bg-[#17385f] px-3 py-2 text-white">Edit</button></td>}</tr>)}</tbody></table><p className="p-3 text-xs text-black/50">{filtered.length} records · Staging only</p></div>}</div></main>;
}
