"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase-browser";
const TENANT="3ebc2265-8842-4826-b464-71783d6cf841";
const resources=["jobs","customers","payments","costs","quotes","invoices","files","people","assignments","audit"];
export default function MjOperationalJob({reference}:{reference:string}){
 const [token,setToken]=useState(""),[data,setData]=useState<Record<string,any[]>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setToken(data.session?.access_token||""));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setToken(s?.access_token||""));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!token)return;let active=true;Promise.all(resources.map(async resource=>{const response=await fetch("/api/business-software/tenant-data?"+new URLSearchParams({tenant_id:TENANT,resource}),{headers:{Authorization:"Bearer "+token},cache:"no-store"});const body=await response.json();if(!response.ok)throw Error(body.error||"Cannot load "+resource);return [resource,body.data] as const})).then(all=>{if(active)setData(Object.fromEntries(all))}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[token]);
 const job=data.jobs?.find(j=>j.reference===reference),customer=data.customers?.find(c=>c.id===job?.customer_id);
 async function edit(){if(!job)return;const allowed=["status","manager","next_action","internal_notes","job_type","customer_requirements"];const field=prompt("Edit field: "+allowed.join(", "));if(!field||!allowed.includes(field))return;const value=prompt("New "+field,String(job[field]??""));if(value===null)return;setBusy(true);try{const r=await fetch("/api/business-software/tenant-update",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({tenant_id:TENANT,resource:"jobs",id:job.id,values:{[field]:value}})});const body=await r.json();if(!r.ok)throw Error(body.error);setData(prev=>({...prev,jobs:prev.jobs.map(j=>j.id===job.id?{...j,[field]:value}:j)}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function download(path:string){try{const r=await fetch("/api/business-software/private-file",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({tenant_id:TENANT,path})});const body=await r.json();if(!r.ok)throw Error(body.error);location.assign(body.url)}catch(e:any){setError(e.message)}}
 return <main className="mx-auto max-w-6xl p-6"><Link href="/bms-runtime/jobs" className="text-sm underline">← Jobs</Link><h1 className="mt-4 text-3xl font-black">{reference}</h1><p className="mb-5 text-sm">M&J isolated staging · Shared BMS</p>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{!token&&<Link href="/bms-mj-preview" className="underline">Sign in to staging</Link>}
 {job?<><div className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">{[customer?.first_name,customer?.last_name].filter(Boolean).join(" ")}</h2><p>{job.job_type} · {job.status}</p><p>Manager: {job.manager||"Unassigned"} · Next: {job.next_action||"—"}</p><p>Quoted: £{Number(job.quoted_amount||0).toLocaleString("en-GB")}</p><button disabled={busy} onClick={edit} className="mt-3 rounded-lg bg-[#17385f] px-4 py-2 text-white">Edit job</button></div>
 {resources.filter(x=>!["jobs","customers"].includes(x)).map(resource=>{const rows=(data[resource]||[]).filter(row=>row.job_id===job.id);return <section key={resource} className="mt-5 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold capitalize">{resource} ({rows.length})</h2>{rows.map(row=><div key={row.id} className="mt-2 border-t py-3 text-sm">{Object.entries(row).filter(([k])=>!["tenant_id"].includes(k)).map(([k,v])=><p key={k}><b>{k.replaceAll("_"," ")}:</b> {v==null?"—":typeof v==="object"?JSON.stringify(v):String(v)}</p>)}{resource==="files"&&row.storage_path&&<button onClick={()=>download(row.storage_path)} className="underline">Download private file</button>}</div>)}</section>})}</>:token?<p>Loading job…</p>:null}</main>;
}
