"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase-browser";
const TENANT="3ebc2265-8842-4826-b464-71783d6cf841";
const money=(v:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(v);
export default function MjOperationalDashboard(){
 const [token,setToken]=useState(""),[data,setData]=useState<Record<string,any[]>>({}),[error,setError]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setToken(data.session?.access_token||""));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setToken(s?.access_token||""));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!token)return;let active=true;Promise.all(["jobs","customers","payments","costs","quotes","invoices"].map(async resource=>{const response=await fetch("/api/business-software/tenant-data?"+new URLSearchParams({tenant_id:TENANT,resource}),{headers:{Authorization:"Bearer "+token},cache:"no-store"});const body=await response.json();if(!response.ok)throw Error(body.error||"Unable to load "+resource);return [resource,body.data]})).then(all=>{if(active)setData(Object.fromEntries(all))}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[token]);
 const jobs=data.jobs||[],payments=data.payments||[],costs=data.costs||[];
 const received=payments.filter(p=>p.direction==="customer_in").reduce((n,p)=>n+Number(p.amount||0),0);
 const contractorPaid=payments.filter(p=>p.direction==="subcontractor_out").reduce((n,p)=>n+Number(p.amount||0),0);
 const actualCosts=costs.reduce((n,c)=>n+Number(c.actual_amount||0),0);
 const customerById=new Map((data.customers||[]).map(c=>[c.id,c]));
 const active=jobs.filter(j=>!["completed","declined","cancelled"].includes(String(j.status||"").toLowerCase()));
 const outstanding=jobs.reduce((n,j)=>n+Math.max(0,Number(j.quoted_amount||0)-payments.filter(p=>p.job_id===j.id&&p.direction==="customer_in"&&p.paid_at).reduce((a,p)=>a+Number(p.amount||0),0)-Number(j.written_off_amount||0)),0);
 const recent=[...jobs].sort((a,b)=>String(b.updated_at||b.created_at||"").localeCompare(String(a.updated_at||a.created_at||""))).slice(0,10);
 const next=[...active].filter(j=>j.next_action).sort((a,b)=>String(a.next_action_at||"9999").localeCompare(String(b.next_action_at||"9999"))).slice(0,6);
 return <main className="mx-auto max-w-7xl px-4 py-6 text-[#172b4d] sm:px-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e66a24]">M&J · Business management</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Dashboard</h1><p className="mt-2 text-sm text-[#172b4d]/60">Shared BMS · Isolated staging</p></div><Link href="/bms-runtime/jobs/new" className="rounded-xl bg-[#e66a24] px-5 py-3 text-sm font-black text-white shadow-sm">+ New job</Link></div>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{!token&&<p className="mt-5"><Link href="/bms-mj-preview" className="font-bold underline">Sign in to M&J staging</Link></p>}
 <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Active jobs",active.length,"/bms-runtime/jobs"],["Customers",(data.customers||[]).length,"/bms-runtime/customers"],["Customer receipts",money(received),"/bms-runtime/payments"],["Quoted outstanding",money(outstanding),"/bms-runtime/quotes"]].map(([label,value,href])=><Link key={String(label)} href={String(href)} className="rounded-2xl border border-[#172b4d]/10 bg-white p-5 shadow-sm transition hover:border-[#e66a24]/60"><p className="text-sm font-semibold text-[#172b4d]/60">{label}</p><p className="mt-3 text-3xl font-black tracking-tight">{value}</p><p className="mt-4 text-xs font-bold text-[#e66a24]">View details →</p></Link>)}</div>
 <div className="mt-4 grid gap-3 sm:grid-cols-3">{[["Recorded job costs",money(actualCosts)],["Contractor payments",money(contractorPaid)],["Receipts less contractor payments",money(received-contractorPaid)]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-[#172b4d]/10 bg-[#f5f5f2] p-5"><p className="text-sm font-semibold text-[#172b4d]/65">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</div><p className="mt-3 text-xs text-[#172b4d]/55">Financial figures reflect recorded staging transactions. Receipts less contractor payments is not profit; other costs, VAT and overheads may apply. Quoted outstanding is an estimate, not an invoiced balance.</p>
 <div className="mt-8 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><section className="overflow-hidden rounded-2xl border border-[#172b4d]/10 bg-white shadow-sm"><div className="flex items-center justify-between border-b bg-[#f5f5f2] px-5 py-4"><h2 className="text-lg font-black">Recent jobs</h2><Link href="/bms-runtime/jobs" className="text-sm font-bold text-[#e66a24]">All jobs →</Link></div>{recent.map(j=>{const c=customerById.get(j.customer_id);return <Link key={j.id} href={"/bms-runtime/jobs/"+j.reference} className="grid gap-2 border-b border-[#172b4d]/10 px-5 py-4 transition hover:bg-[#f5f5f2] sm:grid-cols-[90px_1fr_auto] sm:items-center"><span className="font-black text-[#e66a24]">{j.reference}</span><span className="min-w-0"><span className="block truncate font-bold">{[c?.first_name,c?.last_name].filter(Boolean).join(" ")||j.job_type||"Job"}</span><span className="block truncate text-xs text-[#172b4d]/55">{j.job_type||"Job type not set"} · {j.manager||"Unassigned"}</span></span><span className="w-fit rounded-full bg-[#f5f5f2] px-3 py-1 text-xs font-bold capitalize">{String(j.status||"unknown").replaceAll("_"," ")}</span></Link>})}{recent.length===0&&<p className="p-5 text-sm">No jobs found.</p>}</section><section className="overflow-hidden rounded-2xl border border-[#172b4d]/10 bg-white shadow-sm"><div className="border-b bg-[#f5f5f2] px-5 py-4"><h2 className="text-lg font-black">Next actions</h2><p className="mt-1 text-xs text-[#172b4d]/55">Outstanding work requiring attention</p></div>{next.map(j=><Link key={j.id} href={"/bms-runtime/jobs/"+j.reference} className="block border-b border-[#172b4d]/10 px-5 py-4 transition hover:bg-[#f5f5f2]"><span className="text-xs font-black text-[#e66a24]">{j.reference}</span><p className="mt-1 font-bold">{j.next_action}</p><p className="mt-1 text-xs text-[#172b4d]/55">{j.next_action_at?new Date(j.next_action_at).toLocaleDateString("en-GB"):"No due date"} · {j.manager||"Unassigned"}</p></Link>)}{next.length===0&&<p className="p-5 text-sm">No outstanding actions recorded.</p>}</section></div></main>;
}
