"use client";
import {FormEvent,useEffect,useRef,useState} from "react";

export default function AiAssistantPage(){
 const[question,setQuestion]=useState("");const[answer,setAnswer]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[allowed,setAllowed]=useState<boolean|null>(null);const[recording,setRecording]=useState(false);const[seconds,setSeconds]=useState(0);const recognition=useRef<any>(null);const timer=useRef<any>(null);
 useEffect(()=>{fetch("/api/admin/settings",{cache:"no-store"}).then(async r=>{if(!r.ok){setAllowed(false);return}const b=await r.json();const s=b.settings;setAllowed(Boolean(s?.billing?.mode==="free"||s?.plan?.aiIncluded));}).catch(()=>setAllowed(false));return()=>{if(timer.current)clearInterval(timer.current);recognition.current?.abort?.();};},[]);
 async function ask(e:FormEvent){e.preventDefault();if(!question.trim()||busy)return;setBusy(true);setError("");setAnswer("");const r=await fetch("/api/admin/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});const b=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setError(b.error||"Could not ask AI Assistant");return}setAnswer(String(b.answer||""));}
 function stopRecording(){recognition.current?.stop?.();}
 function listen(){if(recording){stopRecording();return}setError("");const w=window as any;const SpeechRecognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SpeechRecognition){setError("Voice input is not supported by this browser.");return}try{const r=new SpeechRecognition();recognition.current=r;r.lang="en-GB";r.interimResults=true;r.continuous=false;r.onstart=()=>{setRecording(true);setSeconds(0);timer.current=setInterval(()=>setSeconds(s=>s+1),1000);};r.onresult=(event:any)=>{let text="";for(let i=0;i<event.results.length;i++)text+=event.results[i][0]?.transcript||"";setQuestion(text.trim());};r.onerror=(event:any)=>{setError(event?.error==="not-allowed"?"Microphone permission is blocked. Allow microphone access and try again.":"Voice input stopped. Please try again.");};r.onend=()=>{setRecording(false);if(timer.current)clearInterval(timer.current);timer.current=null;};r.start();}catch{setError("Voice input could not start.");}}
 if(allowed===false)return <main className="min-h-screen bg-[#f5f5f2] p-6 lg:p-10"><div className="mx-auto max-w-3xl rounded-2xl border border-black/10 bg-white p-7"><h1 className="text-2xl font-black">AI Assistant</h1><p className="mt-3 text-black/60">AI Assistant is not included in this Business Software subscription.</p></div></main>;
 return <main className="min-h-screen bg-[#f5f5f2] p-5 lg:p-8"><div className="mx-auto max-w-4xl"><p className="text-xs font-black uppercase tracking-[.14em] text-[#e66a24]">Diamant Solutions</p><h1 className="mt-1 text-3xl font-black">AI Assistant</h1><p className="mt-2 text-sm text-black/55">Ask about your business or tell the assistant what you want updated.</p>{answer&&<section className="mt-6 rounded-2xl border border-black/10 bg-white p-6 shadow-sm"><div className="whitespace-pre-wrap text-sm leading-7 text-black/75">{answer}</div></section>}<form onSubmit={ask} className="mt-6"><div className={"rounded-[26px] border bg-white px-4 py-3 shadow-sm transition "+(recording?"border-red-400 ring-2 ring-red-100":"border-black/10 focus-within:border-black/25")}><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit();}}} placeholder="Message AI Assistant" rows={2} className="max-h-44 min-h-14 w-full resize-none bg-transparent px-1 py-2 text-[15px] outline-none"/><div className="flex items-center justify-between gap-3"><button type="button" onClick={listen} aria-label={recording?"Stop recording":"Voice input"} className={"flex h-10 items-center gap-2 rounded-full px-3 text-sm font-bold transition "+(recording?"bg-red-50 text-red-700":"hover:bg-black/5")}>{recording?<><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-red-600"/><span>Recording {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</span></>:<svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v5M8 22h8"/></svg>}</button><button aria-label="Send" disabled={busy||!question.trim()} className="flex h-10 w-10 items-center justify-center rounded-full bg-[#141414] text-xl font-black text-white transition disabled:opacity-25">{busy?<span className="animate-pulse text-sm">•••</span>:<span>↑</span>}</button></div></div>{error&&<p className="mt-3 px-2 text-sm font-bold text-red-700">{error}</p>}</form></div></main>;
}