"use client";
import {useEffect,useState} from "react";
import {supabase,supabaseConfigured} from "../../lib/supabase-browser";

export default function MjLoginPage(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!supabaseConfigured)return;supabase.auth.getSession().then(({data})=>{if(data.session?.access_token)window.location.replace("/")})},[]);
 async function handleSubmit(event){event.preventDefault();setLoading(true);setError("");const {error}=await supabase.auth.signInWithPassword({email,password});setPassword("");if(error){setError("Incorrect email or password");setLoading(false);return}window.location.assign("/");}
 return <main className="min-h-screen bg-[#f5f5f2] px-5 py-12 text-[#141414]"><div className="mx-auto max-w-md rounded-3xl border border-black/10 bg-white p-7 shadow-[0_14px_50px_rgba(0,0,0,0.08)] sm:p-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#e66a24]">Business Software</p><h1 className="mt-2 text-3xl font-black tracking-tight">Sign in</h1><p className="mt-3 text-sm leading-6 text-black/55">Secure access for authorised users.</p>{!supabaseConfigured?<p className="mt-7 rounded-xl bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">Authentication is temporarily unavailable.</p>:<form className="mt-7 space-y-4" onSubmit={handleSubmit}><label className="block"><span className="mb-1.5 block text-sm font-bold">Email</span><input value={email} onChange={e=>setEmail(e.target.value)} required type="email" autoComplete="email" className="h-12 w-full rounded-xl border border-black/15 px-3 outline-none focus:border-[#e66a24]"/></label><label className="block"><span className="mb-1.5 block text-sm font-bold">Password</span><input value={password} onChange={e=>setPassword(e.target.value)} required type="password" autoComplete="current-password" className="h-12 w-full rounded-xl border border-black/15 px-3 outline-none focus:border-[#e66a24]"/></label>{error&&<p className="rounded-xl bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{error}</p>}<button type="submit" disabled={loading} className="h-12 w-full rounded-xl bg-[#e66a24] font-black text-white disabled:opacity-50">{loading?"Signing in...":"Login"}</button></form>}</div></main>;
}
